package ruleset_test

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/forgeplex/appkit/ruleset"
	yaml "go.yaml.in/yaml/v3"
)

var update = flag.Bool("update", false, "重写 golden 文件")

func testConfig() ruleset.Config {
	return ruleset.Config{
		Domain:    "ledger",
		Module:    "github.com/forgeplex/ledger",
		Contracts: "github.com/forgeplex/psp-contracts/go",
		Version:   "v1.2.3",
	}
}

func mustRender(t *testing.T, cfg ruleset.Config) map[string][]byte {
	t.Helper()
	files, err := ruleset.Render(cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	return files
}

func TestRender_文件集与生成头(t *testing.T) {
	files := mustRender(t, testConfig())
	wantHeader := "# Code generated by appkit sync (v1.2.3). DO NOT EDIT.\n"
	for _, rel := range []string{".golangci.yml", ".go-arch-lint.yml", ".github/workflows/ci.yml"} {
		body, ok := files[rel]
		if !ok {
			t.Errorf("缺少输出文件 %s", rel)
			continue
		}
		if !strings.HasPrefix(string(body), wantHeader) {
			t.Errorf("%s 首行不是生成头，实际开头: %q", rel, firstLine(body))
		}
	}
	if len(files) != 3 {
		t.Errorf("输出文件数 = %d, want 3", len(files))
	}
}

func TestRender_默认版本(t *testing.T) {
	cfg := testConfig()
	cfg.Version = ""
	files := mustRender(t, cfg)
	if got := firstLine(files[".golangci.yml"]); !strings.Contains(got, "(devel)") {
		t.Errorf("空 Version 应落为 (devel)，实际生成头: %q", got)
	}
}

func TestRender_合法YAML(t *testing.T) {
	files := mustRender(t, testConfig())
	tests := []struct {
		rel string
		key string // 解析后须存在的顶层 key
	}{
		{".golangci.yml", "linters"},
		{".go-arch-lint.yml", "components"},
		{".github/workflows/ci.yml", "jobs"},
	}
	for _, tt := range tests {
		t.Run(tt.rel, func(t *testing.T) {
			var doc map[string]any
			if err := yaml.Unmarshal(files[tt.rel], &doc); err != nil {
				t.Fatalf("%s 不是合法 YAML: %v", tt.rel, err)
			}
			if _, ok := doc[tt.key]; !ok {
				t.Errorf("%s 缺少顶层 key %q", tt.rel, tt.key)
			}
		})
	}

	// schema 版本必须与工具链核实过的一致。
	var golangci struct {
		Version string `yaml:"version"`
	}
	if err := yaml.Unmarshal(files[".golangci.yml"], &golangci); err != nil {
		t.Fatal(err)
	}
	if golangci.Version != "2" {
		t.Errorf(".golangci.yml version = %q, want \"2\"", golangci.Version)
	}
	var archlint struct {
		Version int `yaml:"version"`
	}
	if err := yaml.Unmarshal(files[".go-arch-lint.yml"], &archlint); err != nil {
		t.Fatal(err)
	}
	if archlint.Version != 3 {
		t.Errorf(".go-arch-lint.yml version = %d, want 3", archlint.Version)
	}
}

func TestRender_域名与模块替换(t *testing.T) {
	files := mustRender(t, testConfig())
	tests := []struct {
		rel   string
		wants []string
	}{
		{".golangci.yml", []string{
			"**/internal/ledger/**",
			"github.com/jackc/pgx",
			"github.com/gin-gonic",
			"net/http",
			"!**/internal/postgres/**",
			`'^fmt\.Print.*$'`,
			"require-explanation: true",
			"require-specific: true",
			"wrapcheck",
			// 组合根持连接池是设计，不是越界：pgx 规则须放行 internal/module
			// 与 cmd/（GUIDE §3 就是这么写的），否则脚手架生成的第一份代码
			// 就被自己的规则集判红。
			"!**/internal/module/**",
			"!**/cmd/**",
			// 框架的错误词汇是 apperr 而非 fmt.Errorf("%w")，
			// 且业务包调自己的 Store 接口是标准形态——两者都不该被 wrapcheck 拦。
			"github.com/forgeplex/appkit**",
			"github.com/jackc/pgx/**",
			"github.com/forgeplex/ledger/internal/postgres/sqlc",
			`^ledger\.`,
		}},
		{".go-arch-lint.yml", []string{
			`"ledger"`,
			`"ledger/**"`,
			"mayDependOn",
			// deepScan 会把组合根的依赖注入判成 domain → postgres，必须关掉。
			"deepScan: false",
		}},
		{".github/workflows/ci.yml", []string{
			"uses: forgeplex/appkit/.github/workflows/domain-ci.yml@main",
			"github.com/forgeplex/ledger",
		}},
	}
	for _, tt := range tests {
		t.Run(tt.rel, func(t *testing.T) {
			body := string(files[tt.rel])
			for _, w := range tt.wants {
				if !strings.Contains(body, w) {
					t.Errorf("%s 缺少片段 %q", tt.rel, w)
				}
			}
		})
	}
}

func TestRender_非法配置(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(*ruleset.Config)
	}{
		{"domain 为空", func(c *ruleset.Config) { c.Domain = "" }},
		{"domain 含大写", func(c *ruleset.Config) { c.Domain = "Ledger" }},
		{"domain 数字开头", func(c *ruleset.Config) { c.Domain = "9ledger" }},
		{"domain 含连字符", func(c *ruleset.Config) { c.Domain = "led-ger" }},
		{"domain 为保留名", func(c *ruleset.Config) { c.Domain = "postgres" }},
		{"module 为空", func(c *ruleset.Config) { c.Module = "" }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := testConfig()
			tt.mutate(&cfg)
			if _, err := ruleset.Render(cfg); err == nil {
				t.Error("want 错误, got nil")
			}
		})
	}
}

func TestRender_Golden(t *testing.T) {
	golden := map[string]string{
		".golangci.yml":            "golangci.yml.golden",
		".go-arch-lint.yml":        "arch-lint.yml.golden",
		".github/workflows/ci.yml": "ci.yml.golden",
	}
	files := mustRender(t, testConfig())
	for rel, name := range golden {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join("testdata", "golden", name)
			if *update {
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, files[rel], 0o644); err != nil {
					t.Fatal(err)
				}
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("读取 golden（可用 go test -update 生成）: %v", err)
			}
			if string(files[rel]) != string(want) {
				t.Errorf("%s 与 golden %s 不一致（如属预期请 go test -update）", rel, path)
			}
		})
	}
}

// appkit 仓库自带的 workflow 文件也必须是合法 YAML（与 ci.yml.tmpl 引用点保持一致）。
func TestWorkflows_合法YAML(t *testing.T) {
	tests := []struct {
		path string
		want string // 文件内须出现的片段
	}{
		{"../.github/workflows/domain-ci.yml", "workflow_call"},
		{"../.github/workflows/ci.yml", "cd lint"},
	}
	for _, tt := range tests {
		t.Run(filepath.Base(tt.path), func(t *testing.T) {
			body, err := os.ReadFile(tt.path)
			if err != nil {
				t.Fatal(err)
			}
			var doc map[string]any
			if err := yaml.Unmarshal(body, &doc); err != nil {
				t.Fatalf("%s 不是合法 YAML: %v", tt.path, err)
			}
			if _, ok := doc["jobs"]; !ok {
				t.Errorf("%s 缺少 jobs", tt.path)
			}
			if !strings.Contains(string(body), tt.want) {
				t.Errorf("%s 缺少片段 %q", tt.path, tt.want)
			}
		})
	}
}

// TestLinterVersionsMatchCI 守住"本地跑的 lint 与 CI 跑的是同一个二进制"。
// 域仓库 Makefile 的 lint 目标由 GolangciLintVersion / ArchLintVersion 渲染，
// domain-ci.yml 里是写死的 go run ...@版本——两处飘了就会出现本地绿、CI 红，
// 而且是最难查的那种（同一份配置、不同版本的检查器）。
func TestLinterVersionsMatchCI(t *testing.T) {
	body, err := os.ReadFile("../.github/workflows/domain-ci.yml")
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		name string
		want string
	}{
		{"golangci-lint", "golangci-lint@" + ruleset.GolangciLintVersion + " "},
		{"go-arch-lint", "go-arch-lint@" + ruleset.ArchLintVersion + " "},
	}
	for _, tt := range tests {
		if !strings.Contains(string(body), tt.want) {
			t.Errorf("domain-ci.yml 未按 %s 的钉版本调用：缺 %q\n"+
				"（改了 ruleset 里的常量就要同步改 workflow，反之亦然）", tt.name, tt.want)
		}
	}
}

func firstLine(b []byte) string {
	s := string(b)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
