// Package ruleset 渲染并分发框架规则集：.golangci.yml、.go-arch-lint.yml
// 与域仓库的 CI 引用文件。模板由 appkit sync 物化进各仓库，CI 做漂移检查
// （见 docs/DESIGN.md §7：物化解决 IDE 集成与 golangci-lint 无配置继承的问题）。
package ruleset

import (
	"bytes"
	"embed"
	"fmt"
	"regexp"
	"text/template"
)

// 域仓库 lint 工具链的钉版本。域仓库的 Makefile（lint 目标）与 appkit 的
// .github/workflows/domain-ci.yml 必须跑同一个版本——版本不一致就会出现
// 「本地绿、CI 红」，而这正是规则集物化要消灭的那类事故。
// 两处一致由 ruleset 的 TestLinterVersionsMatchCI 守住；升级改这里。
const (
	GolangciLintVersion = "v2.13.2"
	ArchLintVersion     = "v1.18.0"
)

//go:embed templates/*.tmpl
var tmplFS embed.FS

var tmpls = template.Must(template.ParseFS(tmplFS, "templates/*.tmpl"))

// Config 是渲染规则集所需的域仓库信息。
type Config struct {
	Domain      string // 业务包名 = Postgres schema，须匹配 ^[a-z][a-z0-9]*$
	Module      string // 域仓库 module path
	Contracts   string // 合约 module path，可空
	Version     string // appkit CLI 版本，写入生成头；空则记为 (devel)
	WorkflowRef string // domain-ci.yml 的完整 40 位 commit SHA
}

// 渲染目标：模板名 → 相对仓库根的落盘路径（恒用斜杠）。
var targets = []struct{ tmpl, path string }{
	{"golangci.yml.tmpl", ".golangci.yml"},
	{"arch-lint.yml.tmpl", ".go-arch-lint.yml"},
	{"ci.yml.tmpl", ".github/workflows/ci.yml"},
}

var domainRE = regexp.MustCompile(`^[a-z][a-z0-9]*$`)

// 与 arch-lint 组件名冲突的保留字，不能用作 domain。
var reservedDomains = map[string]bool{
	"domain": true, "postgres": true, "http": true, "inbox": true, "module": true,
}

func (c Config) validate() error {
	if err := c.validateRepository(); err != nil {
		return err
	}
	if !commitSHARE.MatchString(c.WorkflowRef) {
		return fmt.Errorf("workflow ref %q 不合法：须为完整 40 位 commit SHA", c.WorkflowRef)
	}
	return nil
}

func (c Config) validateRepository() error {
	if !domainRE.MatchString(c.Domain) {
		return fmt.Errorf("domain %q 不合法：须匹配 ^[a-z][a-z0-9]*$", c.Domain)
	}
	if reservedDomains[c.Domain] {
		return fmt.Errorf("domain %q 是保留名（与 arch-lint 组件名冲突），请换名", c.Domain)
	}
	if c.Module == "" {
		return fmt.Errorf("module 不能为空")
	}
	return nil
}

// Render 渲染全部规则集文件；key 是相对仓库根的落盘路径，
// 每个文件均以生成头开始（含 appkit 版本，CI 借此发现版本漂移）。
func Render(cfg Config) (map[string][]byte, error) {
	if cfg.Version == "" {
		cfg.Version = "(devel)"
	}
	if cfg.WorkflowRef == "" {
		workflowRef, err := ResolveWorkflowRef(cfg.Version)
		if err != nil {
			return nil, err
		}
		cfg.WorkflowRef = workflowRef
	}
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	out := make(map[string][]byte, len(targets))
	for _, t := range targets {
		var buf bytes.Buffer
		fmt.Fprintf(&buf, "# Code generated by appkit sync (%s). DO NOT EDIT.\n", cfg.Version)
		if err := tmpls.ExecuteTemplate(&buf, t.tmpl, cfg); err != nil {
			return nil, fmt.Errorf("渲染 %s: %w", t.tmpl, err)
		}
		out[t.path] = buf.Bytes()
	}
	return out, nil
}
