package ruleset_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/forgeplex/appkit/ruleset"
)

const validAppkitYML = `version: 1
domain: ledger
module: github.com/forgeplex/ledger
contracts: github.com/forgeplex/psp-contracts/go
allowRequires: []
`

func writeAppkitYML(t *testing.T, dir, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, ".appkit.yml"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestLoadAppConfig(t *testing.T) {
	tests := []struct {
		name    string
		content string // 空串表示不写文件
		wantErr string // 空串表示应成功
	}{
		{"合法配置", validAppkitYML, ""},
		{"contracts 可空", "version: 1\ndomain: auth\nmodule: github.com/forgeplex/auth\n", ""},
		{"kind domain", "version: 1\nkind: domain\ndomain: auth\nmodule: github.com/forgeplex/auth\n", ""},
		{"kind system 拒绝", "version: 1\nkind: system\ndomain: \"\"\nmodule: github.com/forgeplex/paysys\n", "仅适用于域仓库"},
		{"kind 非法", "version: 1\nkind: infra\ndomain: auth\nmodule: m\n", "非法"},
		{"文件缺失", "", ".appkit.yml"},
		{"version 不为 1", "version: 2\ndomain: ledger\nmodule: m\n", "version 须为 1"},
		{"domain 不合法", "version: 1\ndomain: Ledger\nmodule: m\n", "不合法"},
		{"domain 保留名", "version: 1\ndomain: postgres\nmodule: m\n", "保留名"},
		{"module 为空", "version: 1\ndomain: ledger\n", "module 不能为空"},
		{"未知字段", validAppkitYML + "unknown: x\n", "解析"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			if tt.content != "" {
				writeAppkitYML(t, dir, tt.content)
			}
			cfg, err := ruleset.LoadAppConfig(dir)
			if tt.wantErr == "" {
				if err != nil {
					t.Fatalf("want 成功, got %v", err)
				}
				if cfg.Version != 1 || cfg.Domain == "" {
					t.Errorf("解析结果异常: %+v", cfg)
				}
				return
			}
			if err == nil {
				t.Fatal("want 错误, got nil")
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("错误信息 %q 未包含 %q", err, tt.wantErr)
			}
		})
	}
}

func TestSync_写入与Check通过(t *testing.T) {
	dir := t.TempDir()
	writeAppkitYML(t, dir, validAppkitYML)

	paths, err := ruleset.Sync(dir, "v0.1.0")
	if err != nil {
		t.Fatalf("Sync: %v", err)
	}
	want := []string{".github/workflows/ci.yml", ".go-arch-lint.yml", ".golangci.yml"}
	if len(paths) != len(want) {
		t.Fatalf("写入文件数 = %d, want %d", len(paths), len(want))
	}
	for i, rel := range want {
		if paths[i] != rel {
			t.Errorf("paths[%d] = %q, want %q", i, paths[i], rel)
		}
		body, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
		if err != nil {
			t.Fatalf("读取 %s: %v", rel, err)
		}
		if !strings.HasPrefix(string(body), "# Code generated by appkit sync (v0.1.0). DO NOT EDIT.\n") {
			t.Errorf("%s 缺少生成头", rel)
		}
	}

	if err := ruleset.Check(dir, "v0.1.0"); err != nil {
		t.Errorf("刚写入即漂移: %v", err)
	}
	// 版本变化 = 生成头变化 = 漂移。
	if err := ruleset.Check(dir, "v0.2.0"); err == nil {
		t.Error("版本升级后 Check 应报漂移")
	}

	// Sync 幂等：重跑后内容不变。
	if _, err := ruleset.Sync(dir, "v0.1.0"); err != nil {
		t.Fatalf("重跑 Sync: %v", err)
	}
	if err := ruleset.Check(dir, "v0.1.0"); err != nil {
		t.Errorf("重跑 Sync 后漂移: %v", err)
	}
}

func TestCheck_漂移检测(t *testing.T) {
	tests := []struct {
		name    string
		tamper  func(t *testing.T, dir string)
		wantErr []string
	}{
		{
			"内容被手改",
			func(t *testing.T, dir string) {
				t.Helper()
				path := filepath.Join(dir, ".golangci.yml")
				f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
				if err != nil {
					t.Fatal(err)
				}
				defer f.Close()
				if _, err := f.WriteString("# 手改\n"); err != nil {
					t.Fatal(err)
				}
			},
			[]string{".golangci.yml", "内容漂移"},
		},
		{
			"文件被删除",
			func(t *testing.T, dir string) {
				t.Helper()
				if err := os.Remove(filepath.Join(dir, ".github", "workflows", "ci.yml")); err != nil {
					t.Fatal(err)
				}
			},
			[]string{".github/workflows/ci.yml", "缺失"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAppkitYML(t, dir, validAppkitYML)
			if _, err := ruleset.Sync(dir, "v0.1.0"); err != nil {
				t.Fatal(err)
			}
			tt.tamper(t, dir)
			err := ruleset.Check(dir, "v0.1.0")
			if err == nil {
				t.Fatal("want 漂移错误, got nil")
			}
			for _, w := range tt.wantErr {
				if !strings.Contains(err.Error(), w) {
					t.Errorf("错误信息 %q 未包含 %q", err, w)
				}
			}
		})
	}
}

func TestCheck_缺少配置文件(t *testing.T) {
	err := ruleset.Check(t.TempDir(), "v0.1.0")
	if err == nil || !strings.Contains(err.Error(), ".appkit.yml") {
		t.Errorf("应报 .appkit.yml 缺失, got %v", err)
	}
}
