// Package agentplan builds reviewable plans from AppKit's existing generators.
// It does not execute generators supplied by the workspace or change files.
// Schema planning additionally runs explicitly authorized, trusted migration SQL
// in a disposable database; applying that captured output needs no database.
package agentplan

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"

	"github.com/forgeplex/appkit/internal/gen"
	"github.com/forgeplex/appkit/internal/workspace"
	"github.com/forgeplex/appkit/ruleset"
)

// Sync plans the same three generated files as ruleset.Sync. The configuration
// is an asserted input, so editing it invalidates an outstanding plan.
func Sync(ctx context.Context, root, version string) (workspace.Plan, error) {
	ref, err := ruleset.ResolveWorkflowRefContext(ctx, version)
	if err != nil {
		return workspace.Plan{}, err
	}
	return SyncPinned(ctx, root, version, ref)
}

// SyncPinned plans with an explicit immutable workflow source, without external
// resolution. No git/download command runs while the workspace lock is held.
func SyncPinned(ctx context.Context, root, version, workflowRef string) (workspace.Plan, error) {
	ref, err := ruleset.NormalizeWorkflowRef(workflowRef)
	if err != nil {
		return workspace.Plan{}, err
	}
	return build(ctx, root, ".appkit.yml", func(data []byte) (map[string][]byte, error) {
		cfg, err := ruleset.ParseAppConfig(data)
		if err != nil {
			return nil, err
		}
		return ruleset.Render(ruleset.Config{
			Domain: cfg.Domain, Module: cfg.Module, Contracts: cfg.Contracts, Version: version, WorkflowRef: ref,
		})
	})
}

// Contract plans the generated contract package. Input and target are portable
// paths relative to root; target may be ".". The YAML is also an asserted input.
func Contract(ctx context.Context, root, input, target string) (workspace.Plan, error) {
	if !relative(input) || !(target == "." || relative(target)) {
		return workspace.Plan{}, fmt.Errorf("%w: -in and -target must be normalized workspace-relative paths", workspace.ErrInvalidPath)
	}
	return build(ctx, root, input, func(data []byte) (map[string][]byte, error) {
		files, err := gen.RenderContractSource(input, data)
		if err != nil {
			return nil, err
		}
		out := make(map[string][]byte, len(files))
		for name, content := range files {
			out[path.Join(target, name)] = content
		}
		return out, nil
	})
}

func relative(name string) bool {
	return name != "." && fs.ValidPath(name) && !strings.ContainsAny(name, "\\:")
}

func build(ctx context.Context, root, source string, render func([]byte) (map[string][]byte, error)) (plan workspace.Plan, err error) {
	err = workspace.WithReadLock(ctx, root, func() error {
		// Capture before rendering, and compare with BuildPlan's later snapshot:
		// never bind old generated bytes to a newly edited source/target state.
		data, input, err := workspace.ReadFile(root, source, workspace.MaxPlanContentBytes)
		if err != nil {
			return err
		}
		if !input.Exists {
			return fmt.Errorf("input %q: %w", source, fs.ErrNotExist)
		}
		files, err := render(data)
		if err != nil {
			return err
		}
		if _, overlaps := files[source]; overlaps {
			return fmt.Errorf("%w: generated output overlaps input %q", workspace.ErrInvalidChange, source)
		}
		names := make([]string, 0, len(files))
		for name := range files {
			names = append(names, name)
		}
		sort.Strings(names)
		states := map[string]workspace.File{source: input}
		changes := []workspace.Change{{Path: source, Operation: workspace.OperationAssert}}
		for _, name := range names {
			if err := ctx.Err(); err != nil {
				return err
			}
			content, state, err := workspace.ReadFile(root, name, workspace.MaxPlanContentBytes)
			if err != nil {
				return err
			}
			states[name] = state
			change := workspace.Change{Path: name, Operation: workspace.OperationAssert}
			switch {
			case !state.Exists:
				change.Operation, change.Content, change.Mode = workspace.OperationCreate, files[name], 0o644
			case !bytes.Equal(content, files[name]):
				change.Operation, change.Content, change.Mode = workspace.OperationUpdate, files[name], state.Mode
			}
			changes = append(changes, change)
		}
		plan, err = workspace.BuildPlan(root, changes)
		if err != nil {
			return err
		}
		for _, state := range plan.Preconditions() {
			if state != states[state.Path] {
				return fmt.Errorf("%w: %s changed while planning", workspace.ErrChanged, state.Path)
			}
		}
		return nil
	})
	if err != nil {
		return workspace.Plan{}, err
	}
	return plan, nil
}
