package agentplan

import (
	"context"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/forgeplex/appkit/internal/schemadoc"
	"github.com/forgeplex/appkit/internal/workspace"
)

func schemaFixture(t *testing.T, partitioned bool) string {
	t.Helper()
	root := domain(t)
	if partitioned {
		put(t, root, ".appkit.yml", "version: 1\ndomain: sample\nmodule: example.com/sample\npartitioned: true\n")
	}
	put(t, root, "db/migrations/0001_init.sql", "CREATE TABLE orders (id bigint PRIMARY KEY, merchant_id uuid);\n")
	return root
}

func fakeSchema(ctx context.Context, opts schemadoc.Options) (schemadoc.Schema, error) {
	return schemadoc.Schema{Name: opts.Schema, LogicalTemplate: opts.Partitioned, Tables: []schemadoc.Table{
		{Name: "orders", Kind: schemadoc.KindTable, Columns: []schemadoc.Column{{Name: "id", Type: "bigint", NotNull: true}}},
	}}, ctx.Err()
}

func TestCapturedMigrationFS(t *testing.T) {
	input := map[string][]byte{"0001.sql": []byte("select 1"), "notes/example.md": []byte("nested")}
	captured := newCapturedFS(input, "empty.sql", "nested/empty")
	input["0001.sql"][0] = '!'
	if err := fstest.TestFS(captured, "0001.sql", "notes/example.md", "empty.sql", "nested/empty"); err != nil {
		t.Fatal(err)
	}
	data, err := fs.ReadFile(captured, "0001.sql")
	if err != nil || string(data) != "select 1" {
		t.Fatalf("not detached: %q %v", data, err)
	}
	data[0] = '!'
	again, _ := fs.ReadFile(captured, "0001.sql")
	if string(again) != "select 1" {
		t.Fatal("returned bytes alias captured data")
	}
}

func TestSchemaPlanPreservesEmptyMigrationDirectories(t *testing.T) {
	root := schemaFixture(t, false)
	if err := os.Mkdir(filepath.Join(root, "db/migrations/0002.sql"), 0o755); err != nil {
		t.Fatal(err)
	}
	// Production pgmigrate.Glob("*.sql") includes directories; the subsequent
	// ReadFile must fail identically for a snapshot, not silently ignore it.
	_, err := schemaPlan(context.Background(), root, "", func(ctx context.Context, opts schemadoc.Options) (schemadoc.Schema, error) {
		names, err := fs.Glob(opts.Migrations, "*.sql")
		if err != nil || !reflect.DeepEqual(names, []string{"0001_init.sql", "0002.sql"}) {
			t.Fatalf("captured directory disappeared from SQL inputs: %v %v", names, err)
		}
		_, err = fs.ReadFile(opts.Migrations, "0002.sql")
		return schemadoc.Schema{}, err
	})
	if err == nil {
		t.Fatal("SQL-named empty directory silently ignored")
	}
}

func TestSchemaPlanRoundTripApplyReplayAndParity(t *testing.T) {
	for _, partitioned := range []bool{false, true} {
		t.Run(map[bool]string{false: "domain", true: "logical-template"}[partitioned], func(t *testing.T) {
			root := schemaFixture(t, partitioned)
			put(t, root, "db/schema/stale.sql", "-- Code generated by appkit schema. DO NOT EDIT.\nstale")
			put(t, root, "db/schema/orders.sql", "-- Code generated by appkit schema. DO NOT EDIT.\nold version")
			if err := os.Chmod(filepath.Join(root, "db/schema/orders.sql"), 0o600); err != nil {
				t.Fatal(err)
			}
			before := expandedTree(t, root)
			plan, err := schemaPlan(context.Background(), root, "secret-dsn", fakeSchema)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(before, expandedTree(t, root)) {
				t.Fatal("schema planner wrote repository files")
			}
			again, err := schemaPlan(context.Background(), root, "different-dsn", fakeSchema)
			if err != nil || again.Digest() != plan.Digest() {
				t.Fatalf("schema plan not deterministic or DSN leaked into digest: %v", err)
			}
			encoded, err := workspace.MarshalPlan(plan)
			if err != nil || strings.Contains(string(encoded), "secret-dsn") || !strings.Contains(string(encoded), "workspace-plan/v1alpha2") {
				t.Fatalf("plan wire/secret: %s %v", encoded, err)
			}
			if len(plan.DirectoryGuards()) != 2 {
				t.Fatal("migration and output membership not guarded")
			}
			for _, disposition := range []workspace.ApplyDisposition{workspace.ApplyCommitted, workspace.ApplyReplayed} {
				result, err := workspace.Apply(context.Background(), root, expandedRoundTrip(t, plan))
				if err != nil || result.Disposition != disposition {
					t.Fatalf("schema apply: %+v %v", result, err)
				}
			}
			model, _ := fakeSchema(context.Background(), schemadoc.Options{Schema: "sample", Partitioned: partitioned})
			want, err := schemadoc.Render(model)
			if err != nil {
				t.Fatal(err)
			}
			for name, data := range want {
				got, err := os.ReadFile(filepath.Join(root, name))
				if err != nil || string(got) != data {
					t.Fatalf("renderer parity %s: %v", name, err)
				}
				if partitioned && !strings.Contains(string(got), "logical-template") {
					t.Fatalf("missing template label: %s", name)
				}
			}
			if _, err := os.Stat(filepath.Join(root, "db/schema/stale.sql")); !errors.Is(err, fs.ErrNotExist) {
				t.Fatalf("stale generated output retained: %v", err)
			}
			info, err := os.Stat(filepath.Join(root, "db/schema/orders.sql"))
			if err != nil || info.Mode().Perm() != 0o600 {
				t.Fatalf("output mode not preserved: %v %v", info, err)
			}
			clean, err := schemaPlan(context.Background(), root, "", fakeSchema)
			if err != nil {
				t.Fatal(err)
			}
			for _, change := range clean.Changes() {
				if change.Operation != workspace.OperationAssert {
					t.Fatalf("clean output mutation: %+v", change)
				}
			}
		})
	}
}

func TestSchemaPlanRejectsDriftAndConcurrentEdits(t *testing.T) {
	for _, drift := range []string{"config", "migration-content", "migration-add", "migration-remove", "migration-rename", "output-content", "output-add", "output-remove", "output-dir"} {
		for _, duringRender := range []bool{false, true} {
			t.Run(drift+map[bool]string{true: "/planning", false: "/apply"}[duringRender], func(t *testing.T) {
				root := schemaFixture(t, false)
				put(t, root, "db/schema/stale.sql", "-- Code generated by appkit schema. DO NOT EDIT.\nstale")
				mutate := func() {
					var err error
					switch drift {
					case "config":
						put(t, root, ".appkit.yml", "changed configuration")
					case "migration-content":
						put(t, root, "db/migrations/0001_init.sql", "select 'changed';")
					case "migration-add":
						put(t, root, "db/migrations/0002_new.sql", "select 1;")
					case "migration-remove":
						err = os.Remove(filepath.Join(root, "db/migrations/0001_init.sql"))
					case "migration-rename":
						err = os.Rename(filepath.Join(root, "db/migrations/0001_init.sql"), filepath.Join(root, "db/migrations/0002_renamed.sql"))
					case "output-content":
						put(t, root, "db/schema/stale.sql", "handwritten edit")
					case "output-add":
						put(t, root, "db/schema/handwritten.md", "must not prune")
					case "output-remove":
						err = os.Remove(filepath.Join(root, "db/schema/stale.sql"))
					case "output-dir":
						err = os.Mkdir(filepath.Join(root, "db/schema/new-empty-dir"), 0o755)
					}
					if err != nil {
						t.Fatal(err)
					}
				}
				render := fakeSchema
				if duringRender {
					render = func(ctx context.Context, opts schemadoc.Options) (schemadoc.Schema, error) {
						mutate()
						// Introspection must still consume original captured bytes.
						got, err := fs.ReadFile(opts.Migrations, "0001_init.sql")
						if err != nil || !strings.Contains(string(got), "CREATE TABLE") {
							t.Fatalf("introspection source not captured: %q %v", got, err)
						}
						return fakeSchema(ctx, opts)
					}
				}
				plan, err := schemaPlan(context.Background(), root, "", render)
				if !duringRender {
					if err != nil {
						t.Fatal(err)
					}
					mutate()
					before := expandedTree(t, root)
					_, err = workspace.Apply(context.Background(), root, expandedRoundTrip(t, plan))
					if !reflect.DeepEqual(before, expandedTree(t, root)) {
						t.Fatal("conflicted apply wrote files")
					}
				}
				if !errors.Is(err, workspace.ErrChanged) {
					t.Fatalf("drift accepted: %v", err)
				}
			})
		}
	}
}

func TestSchemaPlanOwnershipValidationAndCancellation(t *testing.T) {
	for _, name := range []string{"db/SCHEMA.md", "db/schema/notes.md", "db/schema/orders.sql"} {
		t.Run(name, func(t *testing.T) {
			root := schemaFixture(t, false)
			put(t, root, name, "handwritten must survive")
			called := false
			_, err := schemaPlan(context.Background(), root, "", func(context.Context, schemadoc.Options) (schemadoc.Schema, error) {
				called = true
				return schemadoc.Schema{}, nil
			})
			if !errors.Is(err, workspace.ErrInvalidChange) || called {
				t.Fatalf("ownership must reject before SQL execution: %v called=%v", err, called)
			}
			got, _ := os.ReadFile(filepath.Join(root, name))
			if string(got) != "handwritten must survive" {
				t.Fatal("handwritten file overwritten")
			}
		})
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := schemaPlan(ctx, schemaFixture(t, false), "", fakeSchema); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancellation ignored: %v", err)
	}
	root := domain(t)
	if _, err := schemaPlan(context.Background(), root, "", fakeSchema); !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("missing migrations accepted: %v", err)
	}
}

func TestSchemaPlanRealDatabase(t *testing.T) {
	dsn := os.Getenv("TEST_DATABASE_URL")
	if dsn == "" {
		t.Skip("TEST_DATABASE_URL not set")
	}
	for _, partitioned := range []bool{false, true} {
		t.Run(map[bool]string{true: "logical-template", false: "domain"}[partitioned], func(t *testing.T) {
			root := schemaFixture(t, partitioned)
			before := expandedTree(t, root)
			plan, err := Schema(context.Background(), root, dsn)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(before, expandedTree(t, root)) {
				t.Fatal("real schema plan changed repository")
			}
			for _, disposition := range []workspace.ApplyDisposition{workspace.ApplyCommitted, workspace.ApplyReplayed} {
				result, err := workspace.Apply(context.Background(), root, expandedRoundTrip(t, plan))
				if err != nil || result.Disposition != disposition {
					t.Fatalf("apply: %+v %v", result, err)
				}
			}
			if _, err := schemadoc.Check(context.Background(), schemadoc.Options{Dir: root, DSN: dsn, Schema: "sample", Partitioned: partitioned}); err != nil {
				t.Fatalf("applied plan fails ordinary schema check: %v", err)
			}
		})
	}
}
