package dbaccess

import (
	"bytes"
	"os"
	"strings"
	"testing"
)

func TestRenderSQLIsDeterministicAndSafe(t *testing.T) {
	m, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	one, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	two, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(one, two) {
		t.Fatal("render output is not deterministic")
	}
	golden, err := os.ReadFile("testdata/access.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(one, golden) {
		t.Fatalf("render output differs from golden:\ngot:\n%s\nwant:\n%s", one, golden)
	}
	text := string(one)
	for _, want := range []string{
		"Code generated by appkit db-access. DO NOT EDIT.",
		`SELECT pg_advisory_xact_lock(hashtextextended('appkit:db-access:role:app_admin_api', 0));`,
		`CREATE ROLE "app_admin_api" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT`,
		`WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role`,
		`GRANT "app_admin_api" TO "psp_admin_api";`,
		`GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";`,
		`GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";`,
		`ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY;`,
		`ALTER TABLE "merchant"."admin_account" FORCE ROW LEVEL SECURITY;`,
		`RAISE EXCEPTION 'required RLS policy % is missing on %', 'admin_account_tenant_isolation', 'merchant.admin_account';`,
		`REVOKE DELETE, INSERT, TRIGGER, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";`,
		`REVOKE INSERT (%I), UPDATE (%I) ON TABLE %I.%I FROM %I`,
		`REVOKE TRIGGER, TRUNCATE ON TABLE "merchant"."admin_account" FROM "app_admin_api";`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("rendered SQL missing %q:\n%s", want, text)
		}
	}
	assertion := strings.Index(text, "required RLS policy % is missing")
	enable := strings.Index(text, `ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY`)
	if assertion < 0 || enable < 0 || assertion > enable {
		t.Fatal("required RLS policy assertion must precede ENABLE/FORCE")
	}
}

func TestRenderSQLCanonicalizesSetAndMapOrder(t *testing.T) {
	left, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	right, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	left.Memberships.Required = []string{"app_zeta", "app_admin_channel_test", "app_alpha"}
	right.Memberships.Required = []string{"app_alpha", "app_admin_channel_test", "app_zeta"}
	left.Grants.Schemas = map[string][]string{"merchant": {"USAGE"}, "payment": {"USAGE"}}
	right.Grants.Schemas = map[string][]string{"payment": {"USAGE"}, "merchant": {"USAGE"}}
	left.Grants.Tables["merchant.admin_account"] = []string{"UPDATE", "SELECT", "INSERT"}
	right.Grants.Tables["merchant.admin_account"] = []string{"INSERT", "UPDATE", "SELECT"}
	left.Forbidden.RoleAttributes = []string{"SUPERUSER", "CREATEDB", "BYPASSRLS", "CREATEROLE"}
	right.Forbidden.RoleAttributes = []string{"CREATEROLE", "BYPASSRLS", "CREATEDB", "SUPERUSER"}
	left.RLS["merchant.admin_account"] = RLSRequirement{Enabled: true, Forced: true, RequiredPolicies: []string{"z_policy", "admin_account_tenant_isolation", "a_policy"}}
	right.RLS["merchant.admin_account"] = RLSRequirement{Enabled: true, Forced: true, RequiredPolicies: []string{"a_policy", "admin_account_tenant_isolation", "z_policy"}}

	leftSQL, err := RenderSQL(*left)
	if err != nil {
		t.Fatal(err)
	}
	rightSQL, err := RenderSQL(*right)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(leftSQL, rightSQL) {
		t.Fatalf("semantic set/map order changed output:\nleft:\n%s\nright:\n%s", leftSQL, rightSQL)
	}
}
