package dbaccess

import (
	"bytes"
	"strings"
	"testing"
)

func TestRenderSQLIsDeterministicAndSafe(t *testing.T) {
	m, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	one, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	two, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(one, two) {
		t.Fatal("render output is not deterministic")
	}
	text := string(one)
	for _, want := range []string{
		"Code generated by appkit db-access. DO NOT EDIT.",
		`CREATE ROLE "app_admin_api" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT`,
		`GRANT "app_admin_api" TO "psp_admin_api";`,
		`GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";`,
		`GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";`,
		`REVOKE DELETE, INSERT, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";`,
		"COMMIT;",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("rendered SQL missing %q:\n%s", want, text)
		}
	}
}
