package dbaccess

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"
)

func RenderSQL(m Manifest) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}
	normalized, err := normalizedYAML(m)
	if err != nil {
		return nil, fmt.Errorf("规范化数据库权限 manifest: %w", err)
	}
	digest := sha256.Sum256(normalized)
	permission := quoteIdentifier(m.Roles.Permission.Name)
	login := quoteIdentifier(m.Roles.Login.Name)

	var b strings.Builder
	fmt.Fprintf(&b, "-- Code generated by appkit db-access. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "-- service: %s\n-- manifest-sha256: %x\n", m.Service, digest)
	b.WriteString("-- Append this output as a new migration; never replace an applied migration.\n\n")
	fmt.Fprintf(&b, "DO $appkit$\nBEGIN\n    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %s) THEN\n", quoteLiteral(m.Roles.Permission.Name))
	b.WriteString("        BEGIN\n")
	fmt.Fprintf(&b, "            CREATE ROLE %s NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT;\n", permission)
	b.WriteString("        EXCEPTION\n            WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role\n        END;\n")
	b.WriteString("    END IF;\nEND\n$appkit$;\n")
	fmt.Fprintf(&b, "ALTER ROLE %s NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE %s;\n\n", permission, inheritKeyword(m.Roles.Permission.Attributes.Inherit))
	fmt.Fprintf(&b, "GRANT %s TO %s;\n", permission, login)
	for _, role := range sortedUnique(m.Memberships.Required) {
		fmt.Fprintf(&b, "GRANT %s TO %s;\n", quoteIdentifier(role), login)
	}
	for _, role := range sortedUnique(m.Memberships.Forbidden) {
		fmt.Fprintf(&b, "REVOKE %s FROM %s;\n", quoteIdentifier(role), login)
	}

	renderGrantMap(&b, "SCHEMA", m.Grants.Schemas, permission)
	renderGrantMap(&b, "TABLE", m.Grants.Tables, permission)
	renderGrantMap(&b, "SEQUENCE", m.Grants.Sequences, permission)

	columns := append([]ColumnGrant(nil), m.Grants.Columns...)
	sort.Slice(columns, func(i, j int) bool {
		return columns[i].Schema+"."+columns[i].Table+"."+columns[i].Column < columns[j].Schema+"."+columns[j].Table+"."+columns[j].Column
	})
	for _, grant := range columns {
		privileges := sortedUnique(grant.Privileges)
		for _, privilege := range privileges {
			fmt.Fprintf(&b, "GRANT %s (%s) ON TABLE %s.%s TO %s;\n", privilege, quoteIdentifier(grant.Column), quoteIdentifier(grant.Schema), quoteIdentifier(grant.Table), permission)
		}
	}

	functions := append([]FunctionGrant(nil), m.Grants.Functions...)
	sort.Slice(functions, func(i, j int) bool { return functionIdentity(functions[i]) < functionIdentity(functions[j]) })
	for _, grant := range functions {
		fmt.Fprintf(&b, "GRANT %s ON FUNCTION %s TO %s;\n", strings.Join(sortedUnique(grant.Privileges), ", "), renderFunctionIdentity(grant), permission)
	}

	renderRLSRequirements(&b, m.RLS)
	renderForbiddenPrivileges(&b, m, permission)
	return []byte(b.String()), nil
}

func renderRLSRequirements(b *strings.Builder, requirements map[string]RLSRequirement) {
	tables := make([]string, 0, len(requirements))
	for table := range requirements {
		tables = append(tables, table)
	}
	sort.Strings(tables)
	for _, table := range tables {
		requirement := requirements[table]
		schema, relation, _ := splitQualifiedName(table) // Validate has already established this invariant.
		for _, policy := range sortedUnique(requirement.RequiredPolicies) {
			fmt.Fprintf(b, "DO $appkit$\nBEGIN\n    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = %s AND tablename = %s AND policyname = %s) THEN\n", quoteLiteral(schema), quoteLiteral(relation), quoteLiteral(policy))
			fmt.Fprintf(b, "        RAISE EXCEPTION 'required RLS policy %% is missing on %%', %s, %s;\n", quoteLiteral(policy), quoteLiteral(table))
			b.WriteString("    END IF;\nEND\n$appkit$;\n")
		}
		fmt.Fprintf(b, "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", quoteQualified(table))
		fmt.Fprintf(b, "ALTER TABLE %s FORCE ROW LEVEL SECURITY;\n", quoteQualified(table))
	}
}

func renderForbiddenPrivileges(b *strings.Builder, m Manifest, role string) {
	revokes := map[string]map[string]bool{}
	add := func(object string, privileges []string) {
		if revokes[object] == nil {
			revokes[object] = map[string]bool{}
		}
		for _, privilege := range privileges {
			revokes[object][privilege] = true
		}
	}
	for object := range m.Grants.Tables {
		add(object, m.Forbidden.Privileges)
	}
	for _, object := range m.Forbidden.Mutations {
		add(object, mutationPrivileges)
		add(object, m.Forbidden.Privileges)
	}
	objects := make([]string, 0, len(revokes))
	for object := range revokes {
		objects = append(objects, object)
	}
	sort.Strings(objects)
	for _, object := range objects {
		privileges := make([]string, 0, len(revokes[object]))
		for privilege := range revokes[object] {
			privileges = append(privileges, privilege)
		}
		sort.Strings(privileges)
		if len(privileges) > 0 {
			fmt.Fprintf(b, "REVOKE %s ON TABLE %s FROM %s;\n", strings.Join(privileges, ", "), quoteQualified(object), role)
		}
	}
}

func renderGrantMap(b *strings.Builder, kind string, grants map[string][]string, role string) {
	names := make([]string, 0, len(grants))
	for name := range grants {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		quoted := quoteIdentifier(name)
		if strings.Contains(name, ".") {
			quoted = quoteQualified(name)
		}
		fmt.Fprintf(b, "GRANT %s ON %s %s TO %s;\n", strings.Join(sortedUnique(grants[name]), ", "), kind, quoted, role)
	}
}

func quoteIdentifier(value string) string { return `"` + value + `"` }

func quoteQualified(value string) string {
	schema, object, _ := splitQualifiedName(value) // Validate has already established this invariant.
	return quoteIdentifier(schema) + "." + quoteIdentifier(object)
}

func quoteLiteral(value string) string { return "'" + strings.ReplaceAll(value, "'", "''") + "'" }

func inheritKeyword(inherit bool) string {
	if inherit {
		return "INHERIT"
	}
	return "NOINHERIT"
}

func sortedUnique(values []string) []string {
	out := append([]string(nil), values...)
	sort.Strings(out)
	return out
}

func functionIdentity(grant FunctionGrant) string {
	return grant.Schema + "." + grant.Name + "(" + strings.Join(grant.Arguments, ",") + ")"
}

func renderFunctionIdentity(grant FunctionGrant) string {
	args := make([]string, len(grant.Arguments))
	for i, arg := range grant.Arguments {
		array := strings.HasSuffix(arg, "[]")
		base := strings.TrimSuffix(arg, "[]")
		parts := strings.Split(base, ".")
		for j := range parts {
			parts[j] = quoteIdentifier(parts[j])
		}
		args[i] = strings.Join(parts, ".")
		if array {
			args[i] += "[]"
		}
	}
	return quoteIdentifier(grant.Schema) + "." + quoteIdentifier(grant.Name) + "(" + strings.Join(args, ", ") + ")"
}
