package dbaccess

import (
	"bytes"
	"os"
	"strings"
	"testing"
)

func TestRenderSQLIsDeterministicAndSafe(t *testing.T) {
	m, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	one, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	two, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(one, two) {
		t.Fatal("render output is not deterministic")
	}
	golden, err := os.ReadFile("testdata/access.sql")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(one, golden) {
		t.Fatalf("render output differs from golden:\ngot:\n%s\nwant:\n%s", one, golden)
	}
	text := string(one)
	for _, want := range []string{
		"Code generated by appkit db-access. DO NOT EDIT.",
		`SELECT pg_advisory_xact_lock(hashtextextended('appkit:db-access:role:app_admin_api', 0));`,
		`CREATE ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT`,
		`WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role`,
		`ALTER ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT;`,
		`GRANT "app_admin_api" TO "psp_admin_api";`,
		`IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin') THEN`,
		`EXECUTE format('REVOKE %I FROM %I', 'app_admin', 'psp_admin_api');`,
		`GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";`,
		`GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";`,
		`GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";`,
		`LOCK TABLE "merchant"."admin_account" IN ACCESS EXCLUSIVE MODE;`,
		`ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY;`,
		`ALTER TABLE "merchant"."admin_account" FORCE ROW LEVEL SECURITY;`,
		`RAISE EXCEPTION 'RLS policy set mismatch on %: expected %, actual %', 'merchant.admin_account', ARRAY['admin_account_tenant_isolation']::text[], appkit_actual_policies;`,
		`RAISE EXCEPTION 'RLS policy % definition mismatch on %', 'admin_account_tenant_isolation', 'merchant.admin_account';`,
		`REVOKE DELETE, INSERT, TRIGGER, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";`,
		`REVOKE INSERT (%I), UPDATE (%I) ON TABLE %I.%I FROM %I`,
		`REVOKE TRIGGER, TRUNCATE ON TABLE "merchant"."admin_account" FROM "app_admin_api";`,
	} {
		if !strings.Contains(text, want) {
			t.Errorf("rendered SQL missing %q:\n%s", want, text)
		}
	}
	lock := strings.Index(text, `LOCK TABLE "merchant"."admin_account" IN ACCESS EXCLUSIVE MODE`)
	assertion := strings.Index(text, "RLS policy set mismatch on %")
	enable := strings.Index(text, `ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY`)
	if lock < 0 || assertion < 0 || enable < 0 || lock > assertion || assertion > enable {
		t.Fatal("table lock and required RLS policy assertion must precede ENABLE/FORCE")
	}
}

func TestRenderSQLRevokesForbiddenPrivilegesFromColumnOnlyTables(t *testing.T) {
	m, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	m.Grants.Tables = nil
	m.Grants.Columns = []ColumnGrant{{Schema: "merchant", Table: "column_only", Column: "visible", Privileges: []string{"SELECT"}}}
	m.RLS = nil
	m.Forbidden.Privileges = []string{"INSERT", "REFERENCES", "UPDATE"}
	m.Forbidden.Mutations = nil
	sql, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`REVOKE INSERT, REFERENCES, UPDATE ON TABLE "merchant"."column_only" FROM "app_admin_api";`,
		`REVOKE INSERT (%I), REFERENCES (%I), UPDATE (%I) ON TABLE %I.%I FROM %I`,
	} {
		if !strings.Contains(string(sql), want) {
			t.Fatalf("column-only table missing forbidden privilege reconciliation %q:\n%s", want, sql)
		}
	}
}

func TestRenderSQLRevokesEveryColumnCapableForbiddenPrivilege(t *testing.T) {
	m, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	m.Grants.Tables = map[string][]string{"merchant.historical_column_acls": {"DELETE"}}
	m.Grants.Columns = nil
	m.RLS = nil
	m.Forbidden.Privileges = append([]string(nil), columnPrivileges...)
	m.Forbidden.Mutations = nil
	sql, err := RenderSQL(*m)
	if err != nil {
		t.Fatal(err)
	}
	want := `REVOKE INSERT (%I), REFERENCES (%I), SELECT (%I), UPDATE (%I) ON TABLE %I.%I FROM %I`
	if !strings.Contains(string(sql), want) {
		t.Fatalf("managed table missing complete forbidden column privilege reconciliation:\n%s", sql)
	}
}

func TestRenderSQLCanonicalizesSetAndMapOrder(t *testing.T) {
	left, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	right, err := Parse(strings.NewReader(validManifest))
	if err != nil {
		t.Fatal(err)
	}
	left.Memberships.Required = []string{"app_zeta", "app_admin_channel_test", "app_alpha"}
	right.Memberships.Required = []string{"app_alpha", "app_admin_channel_test", "app_zeta"}
	left.Grants.Schemas = map[string][]string{"merchant": {"USAGE"}, "payment": {"USAGE"}}
	right.Grants.Schemas = map[string][]string{"payment": {"USAGE"}, "merchant": {"USAGE"}}
	left.Grants.Tables["merchant.admin_account"] = []string{"UPDATE", "SELECT", "INSERT"}
	right.Grants.Tables["merchant.admin_account"] = []string{"INSERT", "UPDATE", "SELECT"}
	left.Forbidden.RoleAttributes = []string{"SUPERUSER", "CREATEDB", "BYPASSRLS", "CREATEROLE"}
	right.Forbidden.RoleAttributes = []string{"CREATEROLE", "BYPASSRLS", "CREATEDB", "SUPERUSER"}
	left.RLS["merchant.admin_account"] = RLSRequirement{Enabled: true, Forced: true, ExactPolicies: true, Policies: []RLSPolicyContract{
		{Name: "z_policy", Command: "SELECT", Mode: "RESTRICTIVE", Roles: []string{"app_zeta", "PUBLIC"}, Using: stringPointer("tenant_id = current_setting('app.tenant_id'::text)")},
		{Name: "admin_account_tenant_isolation", Command: "ALL", Mode: "PERMISSIVE", Roles: []string{"PUBLIC"}, Using: stringPointer("true"), WithCheck: stringPointer("true")},
		{Name: "a_policy", Command: "INSERT", Mode: "PERMISSIVE", Roles: []string{"app_alpha", "PUBLIC"}, WithCheck: stringPointer("true")},
	}}
	right.RLS["merchant.admin_account"] = RLSRequirement{Enabled: true, Forced: true, ExactPolicies: true, Policies: []RLSPolicyContract{
		{Name: "a_policy", Command: "INSERT", Mode: "PERMISSIVE", Roles: []string{"PUBLIC", "app_alpha"}, WithCheck: stringPointer("true")},
		{Name: "admin_account_tenant_isolation", Command: "ALL", Mode: "PERMISSIVE", Roles: []string{"PUBLIC"}, Using: stringPointer("true"), WithCheck: stringPointer("true")},
		{Name: "z_policy", Command: "SELECT", Mode: "RESTRICTIVE", Roles: []string{"PUBLIC", "app_zeta"}, Using: stringPointer("tenant_id = current_setting('app.tenant_id'::text)")},
	}}

	leftSQL, err := RenderSQL(*left)
	if err != nil {
		t.Fatal(err)
	}
	rightSQL, err := RenderSQL(*right)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(leftSQL, rightSQL) {
		t.Fatalf("semantic set/map order changed output:\nleft:\n%s\nright:\n%s", leftSQL, rightSQL)
	}
}

func stringPointer(value string) *string {
	return &value
}
