package dbaccess

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"
)

func RenderSQL(m Manifest) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}
	normalized, err := normalizedYAML(m)
	if err != nil {
		return nil, fmt.Errorf("规范化数据库权限 manifest: %w", err)
	}
	digest := sha256.Sum256(normalized)
	permission := quoteIdentifier(m.Roles.Permission.Name)
	login := quoteIdentifier(m.Roles.Login.Name)
	permissionAttributes := renderPermissionRoleAttributes(m)

	var b strings.Builder
	fmt.Fprintf(&b, "-- Code generated by appkit db-access. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "-- service: %s\n-- manifest-sha256: %x\n", m.Service, digest)
	b.WriteString("-- Append this output as a new migration; never replace an applied migration.\n\n")
	fmt.Fprintf(&b, "SELECT pg_advisory_xact_lock(hashtextextended(%s, 0));\n", quoteLiteral("appkit:db-access:role:"+m.Roles.Permission.Name))
	fmt.Fprintf(&b, "DO $appkit$\nBEGIN\n    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %s) THEN\n", quoteLiteral(m.Roles.Permission.Name))
	b.WriteString("        BEGIN\n")
	fmt.Fprintf(&b, "            CREATE ROLE %s %s;\n", permission, permissionAttributes)
	b.WriteString("        EXCEPTION\n            WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role\n        END;\n")
	b.WriteString("    END IF;\nEND\n$appkit$;\n")
	fmt.Fprintf(&b, "ALTER ROLE %s %s;\n\n", permission, permissionAttributes)
	fmt.Fprintf(&b, "GRANT %s TO %s;\n", permission, login)
	for _, role := range sortedUnique(m.Memberships.Required) {
		fmt.Fprintf(&b, "GRANT %s TO %s;\n", quoteIdentifier(role), login)
	}
	for _, role := range sortedUnique(m.Memberships.Forbidden) {
		renderForbiddenMembership(&b, role, m.Roles.Login.Name)
	}

	renderGrantMap(&b, "SCHEMA", m.Grants.Schemas, permission)
	renderGrantMap(&b, "TABLE", m.Grants.Tables, permission)
	renderGrantMap(&b, "SEQUENCE", m.Grants.Sequences, permission)

	columns := append([]ColumnGrant(nil), m.Grants.Columns...)
	sort.Slice(columns, func(i, j int) bool {
		return columns[i].Schema+"."+columns[i].Table+"."+columns[i].Column < columns[j].Schema+"."+columns[j].Table+"."+columns[j].Column
	})
	for _, grant := range columns {
		privileges := sortedUnique(grant.Privileges)
		for _, privilege := range privileges {
			fmt.Fprintf(&b, "GRANT %s (%s) ON TABLE %s.%s TO %s;\n", privilege, quoteIdentifier(grant.Column), quoteIdentifier(grant.Schema), quoteIdentifier(grant.Table), permission)
		}
	}

	functions := append([]FunctionGrant(nil), m.Grants.Functions...)
	sort.Slice(functions, func(i, j int) bool { return functionIdentity(functions[i]) < functionIdentity(functions[j]) })
	for _, grant := range functions {
		fmt.Fprintf(&b, "GRANT %s ON FUNCTION %s TO %s;\n", strings.Join(sortedUnique(grant.Privileges), ", "), renderFunctionIdentity(grant), permission)
	}

	renderRLSRequirements(&b, m.RLS)
	renderForbiddenPrivileges(&b, m, permission)
	return []byte(b.String()), nil
}

func renderRLSRequirements(b *strings.Builder, requirements map[string]RLSRequirement) {
	tables := make([]string, 0, len(requirements))
	for table := range requirements {
		tables = append(tables, table)
	}
	sort.Strings(tables)
	for _, table := range tables {
		requirement := requirements[table]
		schema, relation, _ := splitQualifiedName(table) // Validate has already established this invariant.
		fmt.Fprintf(b, "LOCK TABLE %s IN ACCESS EXCLUSIVE MODE;\n", quoteQualified(table))
		policies := append([]RLSPolicyContract(nil), requirement.Policies...)
		sort.Slice(policies, func(i, j int) bool { return policies[i].Name < policies[j].Name })
		names := make([]string, len(policies))
		for i, policy := range policies {
			names[i] = policy.Name
		}
		b.WriteString("DO $appkit$\nDECLARE\n    appkit_actual_policies text[];\nBEGIN\n")
		fmt.Fprintf(b, "    SELECT COALESCE(array_agg(p.polname::text ORDER BY p.polname::text), ARRAY[]::text[]) INTO appkit_actual_policies FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %s AND c.relname = %s;\n", quoteLiteral(schema), quoteLiteral(relation))
		fmt.Fprintf(b, "    IF appkit_actual_policies <> %s THEN\n", renderTextArray(names))
		fmt.Fprintf(b, "        RAISE EXCEPTION 'RLS policy set mismatch on %%: expected %%, actual %%', %s, %s, appkit_actual_policies;\n", quoteLiteral(table), renderTextArray(names))
		b.WriteString("    END IF;\n")
		for _, policy := range policies {
			renderRLSPolicyAssertion(b, schema, relation, table, policy)
		}
		b.WriteString("END\n$appkit$;\n")
		fmt.Fprintf(b, "ALTER TABLE %s ENABLE ROW LEVEL SECURITY;\n", quoteQualified(table))
		fmt.Fprintf(b, "ALTER TABLE %s FORCE ROW LEVEL SECURITY;\n", quoteQualified(table))
	}
}

func renderRLSPolicyAssertion(b *strings.Builder, schema, relation, table string, policy RLSPolicyContract) {
	roles := sortedUnique(policy.Roles)
	fmt.Fprintf(b, "    IF NOT EXISTS (SELECT 1 FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %s AND c.relname = %s AND p.polname = %s", quoteLiteral(schema), quoteLiteral(relation), quoteLiteral(policy.Name))
	fmt.Fprintf(b, " AND p.polcmd = %s AND p.polpermissive = %s", quoteLiteral(rlsPolicyCommandCode(policy.Command)), sqlBool(policy.Mode == "PERMISSIVE"))
	fmt.Fprintf(b, " AND ARRAY(SELECT CASE WHEN policy_role.role_oid = 0 THEN 'PUBLIC' ELSE r.rolname::text END FROM unnest(p.polroles) AS policy_role(role_oid) LEFT JOIN pg_roles r ON r.oid = policy_role.role_oid ORDER BY 1) = %s", renderTextArray(roles))
	fmt.Fprintf(b, " AND pg_get_expr(p.polqual, p.polrelid) IS NOT DISTINCT FROM %s", renderNullableText(policy.Using))
	fmt.Fprintf(b, " AND pg_get_expr(p.polwithcheck, p.polrelid) IS NOT DISTINCT FROM %s) THEN\n", renderNullableText(policy.WithCheck))
	fmt.Fprintf(b, "        RAISE EXCEPTION 'RLS policy %% definition mismatch on %%', %s, %s;\n", quoteLiteral(policy.Name), quoteLiteral(table))
	b.WriteString("    END IF;\n")
}

func renderTextArray(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = quoteLiteral(value)
	}
	return "ARRAY[" + strings.Join(quoted, ", ") + "]::text[]"
}

func renderNullableText(value *string) string {
	if value == nil {
		return "NULL"
	}
	return quoteLiteral(*value)
}

func rlsPolicyCommandCode(command string) string {
	return map[string]string{"ALL": "*", "SELECT": "r", "INSERT": "a", "UPDATE": "w", "DELETE": "d"}[command]
}

func sqlBool(value bool) string {
	if value {
		return "TRUE"
	}
	return "FALSE"
}

func renderForbiddenPrivileges(b *strings.Builder, m Manifest, role string) {
	revokes := map[string]map[string]bool{}
	add := func(object string, privileges []string) {
		if revokes[object] == nil {
			revokes[object] = map[string]bool{}
		}
		for _, privilege := range privileges {
			revokes[object][privilege] = true
		}
	}
	for object := range m.Grants.Tables {
		add(object, m.Forbidden.Privileges)
	}
	for _, grant := range m.Grants.Columns {
		add(grant.Schema+"."+grant.Table, m.Forbidden.Privileges)
	}
	for _, object := range m.Forbidden.Mutations {
		add(object, mutationPrivileges)
		add(object, m.Forbidden.Privileges)
	}
	objects := make([]string, 0, len(revokes))
	for object := range revokes {
		objects = append(objects, object)
	}
	sort.Strings(objects)
	for _, object := range objects {
		privileges := make([]string, 0, len(revokes[object]))
		for privilege := range revokes[object] {
			privileges = append(privileges, privilege)
		}
		sort.Strings(privileges)
		if len(privileges) > 0 {
			fmt.Fprintf(b, "REVOKE %s ON TABLE %s FROM %s;\n", strings.Join(privileges, ", "), quoteQualified(object), role)
		}
		renderColumnPrivilegeRevokes(b, object, role, privileges)
	}
}

func renderPermissionRoleAttributes(m Manifest) string {
	attributes := []string{"NOLOGIN"}
	for _, attribute := range sortedUnique(m.Forbidden.RoleAttributes) {
		attributes = append(attributes, "NO"+attribute)
	}
	attributes = append(attributes, inheritKeyword(m.Roles.Permission.Attributes.Inherit))
	return strings.Join(attributes, " ")
}

func renderForbiddenMembership(b *strings.Builder, role, login string) {
	b.WriteString("DO $appkit$\nBEGIN\n")
	fmt.Fprintf(b, "    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %s) THEN\n", quoteLiteral(role))
	fmt.Fprintf(b, "        EXECUTE format('REVOKE %%I FROM %%I', %s, %s);\n", quoteLiteral(role), quoteLiteral(login))
	b.WriteString("    END IF;\nEND\n$appkit$;\n")
}

func renderColumnPrivilegeRevokes(b *strings.Builder, object, role string, privileges []string) {
	var columnRevokes []string
	for _, privilege := range privileges {
		if contains(columnPrivileges, privilege) {
			columnRevokes = append(columnRevokes, privilege)
		}
	}
	if len(columnRevokes) == 0 {
		return
	}
	schema, table, _ := splitQualifiedName(object)
	clauses := make([]string, 0, len(columnRevokes))
	formatArgs := make([]string, 0, len(columnRevokes)+3)
	for _, privilege := range columnRevokes {
		clauses = append(clauses, privilege+" (%I)")
		formatArgs = append(formatArgs, "appkit_column")
	}
	formatArgs = append(formatArgs, quoteLiteral(schema), quoteLiteral(table), quoteLiteral(strings.Trim(role, `"`)))
	b.WriteString("DO $appkit$\nDECLARE\n    appkit_column text;\nBEGIN\n")
	fmt.Fprintf(b, "    FOR appkit_column IN SELECT a.attname FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = %s AND c.relname = %s AND a.attnum > 0 AND NOT a.attisdropped LOOP\n", quoteLiteral(schema), quoteLiteral(table))
	fmt.Fprintf(b, "        EXECUTE format('REVOKE %s ON TABLE %%I.%%I FROM %%I', %s);\n", strings.Join(clauses, ", "), strings.Join(formatArgs, ", "))
	b.WriteString("    END LOOP;\nEND\n$appkit$;\n")
}

func contains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func renderGrantMap(b *strings.Builder, kind string, grants map[string][]string, role string) {
	names := make([]string, 0, len(grants))
	for name := range grants {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		quoted := quoteIdentifier(name)
		if strings.Contains(name, ".") {
			quoted = quoteQualified(name)
		}
		fmt.Fprintf(b, "GRANT %s ON %s %s TO %s;\n", strings.Join(sortedUnique(grants[name]), ", "), kind, quoted, role)
	}
}

func quoteIdentifier(value string) string { return `"` + value + `"` }

func quoteQualified(value string) string {
	schema, object, _ := splitQualifiedName(value) // Validate has already established this invariant.
	return quoteIdentifier(schema) + "." + quoteIdentifier(object)
}

func quoteLiteral(value string) string { return "'" + strings.ReplaceAll(value, "'", "''") + "'" }

func inheritKeyword(inherit bool) string {
	if inherit {
		return "INHERIT"
	}
	return "NOINHERIT"
}

func sortedUnique(values []string) []string {
	out := append([]string(nil), values...)
	sort.Strings(out)
	return out
}

func functionIdentity(grant FunctionGrant) string {
	return grant.Schema + "." + grant.Name + "(" + strings.Join(grant.Arguments, ",") + ")"
}

func renderFunctionIdentity(grant FunctionGrant) string {
	args := make([]string, len(grant.Arguments))
	for i, arg := range grant.Arguments {
		array := strings.HasSuffix(arg, "[]")
		base := strings.TrimSuffix(arg, "[]")
		parts := strings.Split(base, ".")
		for j := range parts {
			parts[j] = quoteIdentifier(parts[j])
		}
		args[i] = strings.Join(parts, ".")
		if array {
			args[i] += "[]"
		}
	}
	return quoteIdentifier(grant.Schema) + "." + quoteIdentifier(grant.Name) + "(" + strings.Join(args, ", ") + ")"
}
