// Command schematool derives sqlc's current schema from migrations in a scratch
// database. Scaffold copies this self-contained tool into domain repositories so
// it works with their existing AppKit dependency (including v0.9.2).
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/signal"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"
	"testing/fstest"
	"time"

	"github.com/forgeplex/appkit"
	"github.com/forgeplex/appkit/pgmigrate"
	"github.com/forgeplex/appkit/ruleset"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	yaml "go.yaml.in/yaml/v3"
)

const snapshotHeader = "-- Code generated by appkit schema tool. DO NOT EDIT.\n"
const snapshotPath = "db/schema.sql"
const lockPath = "db/schema.lock.json"

type manifest struct {
	Format      int               `json:"format"`
	Domain      string            `json:"domain"`
	Partitioned bool              `json:"partitioned"`
	Sources     map[string]string `json:"sources"`
	Snapshot    string            `json:"snapshot_sha256"`
}

func main() {
	if err := command(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func command(args []string) error {
	f := flag.NewFlagSet("schema", flag.ContinueOnError)
	dir := f.String("dir", ".", "domain repository root")
	domain := f.String("domain", "", "logical domain name")
	partitioned := f.Bool("partitioned", false, "prefixless partition template")
	dsn := f.String("dsn", "", "scratch database server; defaults to TEST_DATABASE_URL")
	check := f.Bool("check", false, "regenerate in a scratch database and compare without writing")
	offline := f.Bool("check-source", false, "verify migration, tool and snapshot hashes without a database")
	if err := f.Parse(args); err != nil {
		return err
	}
	if f.NArg() != 0 || !regexp.MustCompile(`^[a-z][a-z0-9]*$`).MatchString(*domain) {
		return errors.New("schema requires -domain (lowercase letters/digits), and no positional arguments")
	}
	if *check && *offline {
		return errors.New("-check and -check-source are mutually exclusive")
	}
	if *offline {
		return checkSource(*dir, *domain, *partitioned)
	}
	if *dsn == "" {
		*dsn = os.Getenv("TEST_DATABASE_URL")
	}
	if *dsn == "" {
		return errors.New("set TEST_DATABASE_URL to a test server with CREATEDB privileges; only a new random database is migrated, never the supplied database")
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	ctx, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	return generate(ctx, *dir, *domain, *partitioned, *dsn, *check)
}

func digest(b []byte) string {
	h := sha256.Sum256(b)
	return hex.EncodeToString(h[:])
}

// Capture once: migrations replayed by pgmigrate and fingerprinted in the lock
// must be the same bytes, even if an editor changes the files during generation.
func capture(dir string) (fstest.MapFS, map[string]string, error) {
	root := filepath.Join(dir, "db/migrations")
	if err := checkPath(dir, "db/migrations"); err != nil {
		return nil, nil, err
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, nil, err
	}
	source := fstest.MapFS{}
	hashes := map[string]string{}
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".sql") {
			continue
		}
		if !regexp.MustCompile(`^[0-9]{4}_[a-zA-Z0-9_]+\.sql$`).MatchString(entry.Name()) {
			return nil, nil, fmt.Errorf("invalid migration filename: %s", entry.Name())
		}
		b, err := readRepoFile(dir, "db/migrations/"+entry.Name())
		if err != nil {
			return nil, nil, err
		}
		source[entry.Name()] = &fstest.MapFile{Data: b, Mode: 0o600}
		hashes["db/migrations/"+entry.Name()] = digest(b)
	}
	if len(source) == 0 {
		return nil, nil, errors.New("no migrations found")
	}
	// These are generated scaffold code, not a new runtime dependency. Changes
	// to the exporter must invalidate an old snapshot just like DDL changes do.
	toolDir := "internal/postgres/schematool"
	if err := checkPath(dir, toolDir); err != nil {
		return nil, nil, err
	}
	toolFiles, err := os.ReadDir(filepath.Join(dir, toolDir))
	if err != nil {
		return nil, nil, err
	}
	paths := []string{".appkit.yml", "go.mod", "go.sum"}
	for _, entry := range toolFiles {
		if strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			paths = append(paths, toolDir+"/"+entry.Name())
		}
	}
	if len(paths) == 3 {
		return nil, nil, errors.New("schema tool source missing")
	}
	for _, rel := range paths {
		b, err := readRepoFile(dir, rel)
		if err != nil {
			return nil, nil, err
		}
		hashes[rel] = digest(b)
	}
	return source, hashes, nil
}

// Only inspect ancestors inside the repository: /tmp and /var may legitimately
// be OS symlinks on macOS. Never follow a repository-controlled directory link.
func checkPath(dir, rel string) error {
	if !fs.ValidPath(filepath.ToSlash(rel)) {
		return fmt.Errorf("invalid repository path: %s", rel)
	}
	path := filepath.Clean(dir)
	for _, part := range strings.Split(filepath.ToSlash(rel), "/") {
		path = filepath.Join(path, part)
		info, err := os.Lstat(path)
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("refuse repository symlink: %s", path)
		}
	}
	return nil
}

func readRepoFile(dir, rel string) ([]byte, error) {
	if err := checkPath(dir, rel); err != nil {
		return nil, err
	}
	return readRegular(filepath.Join(dir, filepath.FromSlash(rel)))
}

func validateConfig(dir, domain string, partitioned bool) error {
	b, err := readRepoFile(dir, ".appkit.yml")
	if err != nil {
		return err
	}
	cfg, err := ruleset.ParseAppConfig(b)
	if err != nil {
		return err
	}
	if cfg.Domain != domain || cfg.Partitioned != partitioned {
		return errors.New("-domain/-partitioned must match .appkit.yml")
	}
	return nil
}

func readRegular(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("refuse non-regular file: %s", path)
	}
	return os.ReadFile(path)
}

// readSQLCState detects adoption separately from the snapshot-only constraints:
// installing the tool must not restrict unadopted repositories' normal tests.
// Explicit generation/check commands validate the supported shape afterwards.
func readSQLCState(dir string) ([]byte, bool, error) {
	config, err := readRepoFile(dir, "sqlc.yaml")
	if err != nil {
		return nil, true, err
	}
	document, err := decodeSQLCConfig(config)
	if err != nil {
		return nil, true, err
	}
	adopted := usesSnapshotSQLC(document)
	for _, path := range []string{snapshotPath, lockPath} {
		_, err := os.Lstat(filepath.Join(dir, path))
		if err == nil {
			adopted = true
		} else if !errors.Is(err, fs.ErrNotExist) {
			return nil, true, err
		}
	}
	return config, adopted, nil
}

func validateSQLC(dir string, allowBootstrap bool) error {
	config, adopted, err := readSQLCState(dir)
	if err != nil {
		return err
	}
	if allowBootstrap && !adopted {
		// First generate the snapshot, then switch sqlc.yaml to it. Even this
		// one-time path requires a single PostgreSQL entry and migration input.
		path, err := sqlcSchemaPath(config)
		if err != nil {
			return err
		}
		if path == "db/migrations" {
			return nil
		}
	}
	return requireSnapshotSQLC(config)
}

// The snapshot gate deliberately covers one PostgreSQL schema input. Decode
// YAML normally so comments, aliases and unrelated nested "schema" fields do
// not change which path sqlc actually uses.
func requireSnapshotSQLC(config []byte) error {
	path, err := sqlcSchemaPath(config)
	if err != nil {
		return err
	}
	if path != snapshotPath {
		return errors.New("snapshot sqlc.yaml must use schema: db/schema.sql")
	}
	return nil
}

func sqlcSchemaPath(config []byte) (string, error) {
	document, err := decodeSQLCConfig(config)
	if err != nil {
		return "", err
	}
	if document["version"] != "2" && document["version"] != 2 {
		return "", errors.New("schema snapshot requires sqlc configuration version 2")
	}
	entries, ok := document["sql"].([]any)
	if !ok || len(entries) != 1 {
		return "", errors.New("schema snapshot requires exactly one sqlc SQL entry")
	}
	entry, ok := entries[0].(map[string]any)
	if !ok || entry["engine"] != "postgresql" {
		return "", errors.New("schema snapshot requires a PostgreSQL sqlc SQL entry")
	}
	input := entry["schema"]
	if paths, ok := input.([]any); ok {
		if len(paths) != 1 {
			return "", errors.New("schema snapshot requires exactly one sqlc schema input")
		}
		input = paths[0]
	}
	path, ok := input.(string)
	if !ok || path == "" {
		return "", errors.New("sqlc schema input must be one nonempty string path")
	}
	return path, nil
}

func decodeSQLCConfig(config []byte) (map[string]any, error) {
	// Decode the entire document, including unknown metadata, so the official
	// decoder rejects duplicate keys and resolves aliases/merges before adoption
	// is detected. Callers decide whether snapshot-specific restrictions apply.
	decoder := yaml.NewDecoder(bytes.NewReader(config))
	var document map[string]any
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("invalid sqlc.yaml: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return nil, errors.New("sqlc.yaml must contain exactly one YAML document")
	}
	return document, nil
}

func usesSnapshotSQLC(document map[string]any) bool {
	// Inspect every actual SQL input, including legacy packages, without treating
	// comments or unrelated metadata as adoption. A snapshot in an unsupported
	// configuration must still activate the strict gate instead of bypassing it.
	for _, key := range []string{"sql", "packages"} {
		entries, _ := document[key].([]any)
		for _, value := range entries {
			entry, _ := value.(map[string]any)
			inputs, ok := entry["schema"].([]any)
			if !ok {
				inputs = []any{entry["schema"]}
			}
			for _, input := range inputs {
				name, ok := input.(string)
				if ok && filepath.ToSlash(filepath.Clean(name)) == snapshotPath {
					return true
				}
			}
		}
	}
	return false
}

func checkSource(dir, domain string, partitioned bool) error {
	if err := validateConfig(dir, domain, partitioned); err != nil {
		return err
	}
	if err := validateSQLC(dir, false); err != nil {
		return err
	}
	_, hashes, err := capture(dir)
	if err != nil {
		return err
	}
	b, err := readRepoFile(dir, lockPath)
	if err != nil {
		return fmt.Errorf("schema lock missing/unreadable; run make schema-sqlc: %w", err)
	}
	var lock manifest
	if err := json.Unmarshal(b, &lock); err != nil {
		return fmt.Errorf("invalid schema lock: %w", err)
	}
	if lock.Format != 1 || lock.Domain != domain || lock.Partitioned != partitioned || len(lock.Sources) != len(hashes) {
		return errors.New("schema source/config drift; run make schema-sqlc")
	}
	for name, hash := range hashes {
		if lock.Sources[name] != hash {
			return fmt.Errorf("schema source drift in %s; run make schema-sqlc", name)
		}
	}
	sql, err := readRepoFile(dir, snapshotPath)
	if err != nil {
		return err
	}
	if !bytes.HasPrefix(sql, []byte(snapshotHeader)) || digest(sql) != lock.Snapshot {
		return errors.New("schema.sql was modified; run make schema-sqlc instead of editing the snapshot")
	}
	return nil
}

func generate(ctx context.Context, dir, domain string, partitioned bool, dsn string, check bool) error {
	if err := validateConfig(dir, domain, partitioned); err != nil {
		return err
	}
	if err := validateSQLC(dir, !check); err != nil {
		return err
	}
	source, hashes, err := capture(dir)
	if err != nil {
		return err
	}
	schema := domain
	if partitioned {
		// sqlc resolves unqualified names against public. This is a compile-time
		// representative, NOT a runtime partition or a cross-domain namespace.
		schema = "public"
	}
	body, err := fromScratch(ctx, dsn, schema, source)
	if err != nil {
		return err
	}
	mode := "fixed domain schema"
	if partitioned {
		mode = "logical partition template in sqlc's public namespace; runtime routing remains prefixless"
	}
	sql := []byte(snapshotHeader + "-- Source: db/migrations. " + mode + ".\n" +
		"-- Current DDL for code generation/review, not a deployment script or database backup.\n" +
		"-- Ownership, grants and sequence runtime state are intentionally not exported.\n\n" + body)
	lock, err := json.MarshalIndent(manifest{Format: 1, Domain: domain, Partitioned: partitioned, Sources: hashes, Snapshot: digest(sql)}, "", "  ")
	if err != nil {
		return err
	}
	lock = append(lock, '\n')
	// Fail rather than publish a snapshot for files that changed during replay.
	_, now, err := capture(dir)
	if err != nil {
		return err
	}
	if len(now) != len(hashes) {
		return errors.New("sources changed while generating; retry")
	}
	for name, hash := range hashes {
		if now[name] != hash {
			return errors.New("sources changed while generating; retry")
		}
	}
	if check {
		for path, want := range map[string][]byte{snapshotPath: sql, lockPath: lock} {
			got, err := readRepoFile(dir, path)
			if err != nil || !bytes.Equal(got, want) {
				return fmt.Errorf("%s differs from fresh migrations; run make schema-sqlc", path)
			}
		}
		return nil
	}
	// Check both destinations before replacing either; never clobber handwritten
	// SQL or follow an output symlink. Per-file atomic replacement + the manifest
	// makes an interrupted two-file update fail closed on the next check.
	for path, marker := range map[string][]byte{snapshotPath: []byte(snapshotHeader), lockPath: []byte("{\n  \"format\": 1,")} {
		b, err := readRepoFile(dir, path)
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if err == nil && !bytes.HasPrefix(b, marker) {
			return fmt.Errorf("refuse to overwrite unowned file %s", path)
		}
	}
	for _, file := range []struct {
		path string
		body []byte
	}{{snapshotPath, sql}, {lockPath, lock}} {
		if err := replaceFile(filepath.Join(dir, file.path), file.body); err != nil {
			return err
		}
	}
	return nil
}

func replaceFile(path string, body []byte) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".schema-*")
	if err != nil {
		return err
	}
	defer os.Remove(f.Name())
	_, writeErr := f.Write(body)
	closeErr := f.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		return err
	}
	if err := os.Chmod(f.Name(), 0o644); err != nil {
		return err
	}
	return os.Rename(f.Name(), path)
}

func fromScratch(ctx context.Context, dsn, schema string, source fs.FS) (body string, resultErr error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return "", safeDBError("parse test database connection", err)
	}
	admin, err := pgx.ConnectConfig(ctx, cfg.ConnConfig.Copy())
	if err != nil {
		return "", safeDBError("connect test database server", err)
	}
	defer func() {
		cctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		resultErr = errors.Join(resultErr, safeDBError("close admin connection", admin.Close(cctx)))
	}()
	var nonce [12]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return "", err
	}
	name := "appkit_sqlc_" + hex.EncodeToString(nonce[:])
	ident := pgx.Identifier{name}.Sanitize()
	created := true // also clean up a CREATE whose response was lost
	defer func() {
		if !created {
			return
		}
		cctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		cleanup, err := pgx.ConnectConfig(cctx, cfg.ConnConfig.Copy())
		if err == nil {
			_, err = cleanup.Exec(cctx, "DROP DATABASE IF EXISTS "+ident+" WITH (FORCE)")
			err = errors.Join(err, cleanup.Close(cctx))
		}
		resultErr = errors.Join(resultErr, safeDBError("clean up scratch database "+name, err))
	}()
	if _, err := admin.Exec(ctx, "CREATE DATABASE "+ident+" TEMPLATE template0"); err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "42P04" {
			created = false
		}
		return "", safeDBError("create scratch database "+name, err)
	}
	tmp := cfg.Copy()
	tmp.ConnConfig.Database = name
	pool, err := pgxpool.NewWithConfig(ctx, tmp)
	if err != nil {
		return "", safeDBError("connect scratch database", err)
	}
	defer pool.Close()
	if err := pgmigrate.Runner(pool)(ctx, []appkit.MigrationSet{{Module: "schema", Schema: schema, FS: source}}); err != nil {
		return "", safeDBError("replay db/migrations in scratch database", err)
	}
	return catalog(ctx, pool, schema)
}

// Never expose a DSN/password through pgx's parse/connect diagnostics.
func safeDBError(op string, err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, context.Canceled) {
		return fmt.Errorf("%s: %w", op, context.Canceled)
	}
	if errors.Is(err, context.DeadlineExceeded) {
		return fmt.Errorf("%s: %w", op, context.DeadlineExceeded)
	}
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) {
		return fmt.Errorf("%s: PostgreSQL SQLSTATE %s", op, pgErr.Code)
	}
	return fmt.Errorf("%s failed (connection details hidden)", op)
}
