package cli

import (
	"bytes"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/forgeplex/appkit/internal/gen"
	"github.com/forgeplex/appkit/internal/scaffold"
	"github.com/forgeplex/appkit/internal/workspace"
)

func TestAgentExpandedGeneratorRoutes(t *testing.T) {
	for _, tc := range []struct {
		name, input, source, target string
		flags                       []string
		render                      func(string, []byte) ([]byte, error)
	}{
		{"events", "events.yaml", "version: 1\npackage: p\nevents: [{name: Created, topic: sample.created}]\n", "events.gen.go", nil, gen.RenderEventsSource},
		{"errors", "codes.yaml", "version: 1\npackage: p\ncodes: [{code: SAMPLE_ERROR, status: 400, message: Error}]\n", "codes.gen.go", nil, gen.RenderErrorsSource},
		{"wrap", "service.go", "package p\nimport \"context\"\ntype Service interface{ Ping(context.Context) error }\n", "wrap.gen.go", []string{"-iface", "Service", "-system", "sample"}, func(name string, data []byte) ([]byte, error) {
			return gen.RenderWrapSources(map[string][]byte{name: data}, "Service", "sample")
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			if err := os.WriteFile(filepath.Join(root, tc.input), []byte(tc.source), 0o644); err != nil {
				t.Fatal(err)
			}
			before := expandedCLIContents(t, root)
			args := append([]string{tc.name, "-dir", root, "-in", tc.input, "-target", tc.target}, tc.flags...)
			encoded, plan := expandedCLIPlan(t, args)
			if !reflect.DeepEqual(before, expandedCLIContents(t, root)) {
				t.Fatal("plan route modified workspace")
			}
			expandedCLIApplyReplay(t, root, encoded, plan)
			want, err := tc.render(tc.input, []byte(tc.source))
			if err != nil {
				t.Fatal(err)
			}
			got, err := os.ReadFile(filepath.Join(root, tc.target))
			if err != nil || !bytes.Equal(got, want) {
				t.Fatalf("CLI generated bytes differ from renderer: %v", err)
			}
		})
	}
}

func TestAgentExpandedNewRoutes(t *testing.T) {
	for _, tc := range []struct {
		name, kind          string
		tenant, partitioned bool
		flags               []string
	}{
		{"domain", "domain", false, false, nil},
		{"tenant", "domain", true, false, []string{"-tenant"}},
		{"partitioned", "domain", false, true, []string{"-partitioned"}},
		{"both", "domain", true, true, []string{"-partitioned", "-tenant"}},
		{"system", "system", false, false, nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			args := append([]string{"new", tc.kind, "sample", "-dir", root, "-target", "generated", "-module", "example.com/sample", "-workflow-ref", agentWorkflowRef}, tc.flags...)
			encoded, plan := expandedCLIPlan(t, args)
			if entries, err := os.ReadDir(root); err != nil || len(entries) != 0 {
				t.Fatalf("new plan route wrote target: %v %v", entries, err)
			}
			expandedCLIApplyReplay(t, root, encoded, plan)
			opts := scaffold.Options{Name: "sample", Module: "example.com/sample", AppkitVersion: Version(), WorkflowRef: agentWorkflowRef, Tenant: tc.tenant, Partitioned: tc.partitioned}
			var expected map[string][]byte
			var err error
			if tc.kind == "domain" {
				expected, err = scaffold.RenderDomain(opts)
			} else {
				expected, err = scaffold.RenderSystem(opts)
			}
			if err != nil {
				t.Fatal(err)
			}
			got := expandedCLIContents(t, filepath.Join(root, "generated"))
			if len(got) != len(expected) {
				t.Fatalf("CLI generated %d files, want %d", len(got), len(expected))
			}
			for name, content := range expected {
				if got[name] != string(content) {
					t.Errorf("CLI scaffold differs at %s", name)
				}
			}
		})
	}
}

func TestAgentExpandedRouteFailuresAreJSON(t *testing.T) {
	for _, args := range [][]string{
		{"events"}, {"errors", "-in", "codes.yaml"}, {"wrap", "-in", "service.go", "-target", "wrap.go"},
		{"new"}, {"new", "domain"}, {"new", "other", "sample"}, {"new", "domain", "sample"},
	} {
		var out, diagnostics bytes.Buffer
		err := runAgent("plan", args, &out, &diagnostics)
		var exit *agentExit
		var result agentResult
		if !errors.As(err, &exit) || exit.code != 2 {
			t.Fatalf("invalid arguments returned %v: %s", err, out.String())
		}
		if err := json.Unmarshal(out.Bytes(), &result); err != nil || result.Error == nil || result.Error.Code != "invalid_arguments" {
			t.Fatalf("invalid arguments not stable JSON: %s %v", out.String(), err)
		}
	}
	root := t.TempDir()
	for _, args := range [][]string{
		{"new", "system", "sample", "-dir", root, "-target", "new", "-tenant"},
		{"new", "system", "sample", "-dir", root, "-target", "new", "-partitioned"},
		{"new", "domain", "sample", "-dir", root, "-target", "../escape"},
	} {
		var out, diagnostics bytes.Buffer
		err := runAgent("plan", args, &out, &diagnostics)
		var result agentResult
		if err == nil {
			t.Fatalf("invalid plan accepted: %v", args)
		}
		if err := json.Unmarshal(out.Bytes(), &result); err != nil || result.Error == nil || result.Error.Code != "invalid_plan" {
			t.Fatalf("invalid plan not stable JSON: %s %v", out.String(), err)
		}
	}
}

func TestAgentExpandedSourceConflictJSON(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "events.yaml")
	if err := os.WriteFile(path, []byte("version: 1\npackage: p\nevents: [{name: Created, topic: sample.created}]\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	encoded, _ := expandedCLIPlan(t, []string{"events", "-dir", root, "-in", "events.yaml", "-target", "events.gen.go"})
	if err := os.WriteFile(path, []byte("changed input"), 0o644); err != nil {
		t.Fatal(err)
	}
	planPath := filepath.Join(t.TempDir(), "plan.json")
	if err := os.WriteFile(planPath, encoded, 0o600); err != nil {
		t.Fatal(err)
	}
	var out, diagnostics bytes.Buffer
	err := runAgent("apply", []string{"-dir", root, "-plan", planPath}, &out, &diagnostics)
	var exit *agentExit
	var result agentResult
	if !errors.As(err, &exit) || exit.code != 3 {
		t.Fatalf("source conflict exit: %v", err)
	}
	if err := json.Unmarshal(out.Bytes(), &result); err != nil || result.Error == nil || result.Error.Code != "workspace_conflict" {
		t.Fatalf("source conflict result: %s %v", out.String(), err)
	}
	if _, err := os.Stat(filepath.Join(root, "events.gen.go")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("conflicting plan wrote target: %v", err)
	}
}

func expandedCLIPlan(t *testing.T, args []string) ([]byte, workspace.Plan) {
	t.Helper()
	var out, diagnostics bytes.Buffer
	if err := runAgent("plan", args, &out, &diagnostics); err != nil {
		t.Fatalf("plan: %v %s", err, out.String())
	}
	plan, err := workspace.ParsePlan(out.Bytes())
	if err != nil || diagnostics.Len() != 0 {
		t.Fatalf("plan stdout is not clean canonical JSON: %v %s", err, diagnostics.String())
	}
	canonical, err := workspace.MarshalPlan(plan)
	if err != nil || !bytes.Equal(canonical, out.Bytes()) {
		t.Fatalf("plan wire changed during round trip: %v", err)
	}
	return bytes.Clone(out.Bytes()), plan
}

func expandedCLIApplyReplay(t *testing.T, root string, encoded []byte, plan workspace.Plan) {
	t.Helper()
	planPath := filepath.Join(t.TempDir(), "plan.json")
	if err := os.WriteFile(planPath, encoded, 0o600); err != nil {
		t.Fatal(err)
	}
	for _, want := range []workspace.ApplyDisposition{workspace.ApplyCommitted, workspace.ApplyReplayed} {
		var out, diagnostics bytes.Buffer
		if err := runAgent("apply", []string{"-dir", root, "-plan", planPath, "-digest", plan.Digest()}, &out, &diagnostics); err != nil {
			t.Fatalf("apply: %v %s", err, out.String())
		}
		var result struct {
			OK   bool           `json:"ok"`
			Data agentApplyData `json:"data"`
		}
		if err := json.Unmarshal(out.Bytes(), &result); err != nil || !result.OK || result.Data.Disposition != want || result.Data.PlanDigest != plan.Digest() || diagnostics.Len() != 0 {
			t.Fatalf("apply result: %s %s %v", out.String(), diagnostics.String(), err)
		}
	}
}

func expandedCLIContents(t *testing.T, root string) map[string]string {
	t.Helper()
	files := map[string]string{}
	if err := filepath.WalkDir(root, func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		data, err := os.ReadFile(name)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		files[filepath.ToSlash(rel)] = string(data)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	return files
}
