package schemadoc

import (
	"fmt"
	"path"
	"slices"
	"sort"
	"strings"
)

// 生成物首行是机器可识别的标准头，与 internal/gen、ruleset 的约定一致。
const (
	sqlHeader = "-- Code generated by appkit schema. DO NOT EDIT.\n" +
		"-- 事实源是 db/migrations；改表结构请新开迁移文件，改本文件不会改变任何东西。\n"
	mdHeader = "<!-- Code generated by appkit schema. DO NOT EDIT. -->\n" +
		"<!-- 事实源是 db/migrations；改表结构请新开迁移文件，改本文件不会改变任何东西。 -->\n"

	noComment = "⚠ 缺说明"
)

// Render 把 Schema 渲染成全部产出（键为仓库相对斜杠路径）。
//
// 纯函数：同一个 Schema 逐字节稳定，因此渲染、分簇、漂移比对都能用零 DB 的
// 单测覆盖，而不必先起一个 Postgres 才敢改一行 Markdown。
func Render(s Schema) (map[string]string, error) {
	s = sorted(s)
	edges := edgesOf(s)
	out := make(map[string]string, len(s.Tables)*2+2)

	for _, t := range s.Tables {
		out[tablePath(t, ".sql")] = renderTableSQL(s.Name, t)
		md, err := renderTableMD(s, t, edges)
		if err != nil {
			return nil, err
		}
		out[tablePath(t, ".md")] = md
	}
	if len(s.Enums) > 0 {
		out[path.Join(schemaDir, enumsFile)] = renderEnumsSQL(s)
	}
	overview, err := renderOverview(s, edges)
	if err != nil {
		return nil, err
	}
	out[docFile] = overview
	return out, nil
}

// sorted 返回按名字排好序的副本，让 Render 的输出与输入顺序无关。
func sorted(s Schema) Schema {
	s.Tables = append([]Table(nil), s.Tables...)
	sort.Slice(s.Tables, func(i, j int) bool { return s.Tables[i].Name < s.Tables[j].Name })
	s.Enums = append([]Enum(nil), s.Enums...)
	sort.Slice(s.Enums, func(i, j int) bool { return s.Enums[i].Name < s.Enums[j].Name })
	return s
}

// ---------- DDL 形态（给 agent 与 grep） ----------

func renderTableSQL(schema string, t Table) string {
	var b strings.Builder
	b.WriteString(sqlHeader)
	b.WriteString("\n")
	if t.Comment != "" {
		fmt.Fprintf(&b, "-- %s\n", strings.ReplaceAll(t.Comment, "\n", "\n-- "))
	}
	qual := schema + "." + t.Name

	if t.Kind != KindTable {
		kw := "VIEW"
		if t.Kind == KindMatView {
			kw = "MATERIALIZED VIEW"
		}
		fmt.Fprintf(&b, "CREATE %s %s AS\n%s\n", kw, qual, strings.TrimRight(t.ViewDef, " \n"))
	} else {
		b.WriteString(renderCreateTable(qual, t))
	}

	if len(t.Indexes) > 0 {
		b.WriteString("\n")
		for _, i := range t.Indexes {
			fmt.Fprintf(&b, "%s;\n", i.Def)
		}
	}
	if len(t.Triggers) > 0 {
		b.WriteString("\n")
		for _, tr := range t.Triggers {
			fmt.Fprintf(&b, "%s;\n", tr.Def)
		}
	}

	var comments strings.Builder
	if t.Comment != "" {
		fmt.Fprintf(&comments, "COMMENT ON TABLE %s IS %s;\n", qual, sqlLiteral(t.Comment))
	}
	for _, c := range t.Columns {
		if c.Comment != "" {
			fmt.Fprintf(&comments, "COMMENT ON COLUMN %s.%s IS %s;\n", qual, c.Name, sqlLiteral(c.Comment))
		}
	}
	if comments.Len() > 0 {
		b.WriteString("\n")
		b.WriteString(comments.String())
	}
	return b.String()
}

func renderCreateTable(qual string, t Table) string {
	nameW, typeW := 0, 0
	for _, c := range t.Columns {
		nameW = max(nameW, len(c.Name))
		typeW = max(typeW, len(c.Type))
	}
	lines := make([]string, 0, len(t.Columns)+len(t.Constraints))
	for _, c := range t.Columns {
		line := fmt.Sprintf("    %-*s %-*s", nameW, c.Name, typeW, c.Type)
		var tail []string
		if c.Identity != "" {
			tail = append(tail, c.Identity)
		}
		if c.NotNull {
			tail = append(tail, "NOT NULL")
		}
		if c.Default != "" {
			tail = append(tail, "DEFAULT "+c.Default)
		}
		lines = append(lines, strings.TrimRight(line+" "+strings.Join(tail, " "), " "))
	}
	for _, c := range orderedConstraints(t) {
		lines = append(lines, fmt.Sprintf("    CONSTRAINT %s %s", c.Name, c.Def))
	}
	return fmt.Sprintf("CREATE TABLE %s (\n%s\n);\n", qual, strings.Join(lines, ",\n"))
}

// orderedConstraints 按 主键 → 唯一 → 外键 → 检查 排列，同类按名字。
// 顺序固定是生成物的硬要求：目录顺序抖一下，PR diff 就会假阳性一整屏。
func orderedConstraints(t Table) []Constraint {
	rank := map[ConstraintType]int{
		ConstraintPrimaryKey: 0, ConstraintUnique: 1,
		ConstraintForeignKey: 2, ConstraintCheck: 3,
	}
	out := append([]Constraint(nil), t.Constraints...)
	sort.Slice(out, func(i, j int) bool {
		if rank[out[i].Type] != rank[out[j].Type] {
			return rank[out[i].Type] < rank[out[j].Type]
		}
		return out[i].Name < out[j].Name
	})
	return out
}

func renderEnumsSQL(s Schema) string {
	var b strings.Builder
	b.WriteString(sqlHeader)
	for _, e := range s.Enums {
		vals := make([]string, len(e.Values))
		for i, v := range e.Values {
			vals[i] = sqlLiteral(v)
		}
		fmt.Fprintf(&b, "\nCREATE TYPE %s.%s AS ENUM (%s);\n", s.Name, e.Name, strings.Join(vals, ", "))
	}
	return b.String()
}

// sqlLiteral 把字符串转成 SQL 单引号字面量。
func sqlLiteral(v string) string {
	return "'" + strings.ReplaceAll(v, "'", "''") + "'"
}

// ---------- 表格形态（给人 review） ----------

func renderTableMD(s Schema, t Table, edges []fkEdge) (string, error) {
	self := tablePath(t, ".md")
	var b strings.Builder
	b.WriteString(mdHeader)
	fmt.Fprintf(&b, "\n# %s.%s\n\n", s.Name, t.Name)
	switch {
	case t.Comment != "":
		fmt.Fprintf(&b, "%s\n", t.Comment)
	case t.Framework():
		// 框架表不标 ⚠：它的 DDL 在 appkit 的库函数里，域仓库改不了自己
		// 那份已应用的 0001——标一个改不动的警告只是噪声。
		fmt.Fprintf(&b, "appkit 基础设施表，由框架建表并维护。\n")
	default:
		fmt.Fprintf(&b, "%s——在建表迁移里补一句 `COMMENT ON TABLE %s.%s IS '…'`。\n", noComment, s.Name, t.Name)
	}
	if t.Kind != KindTable {
		fmt.Fprintf(&b, "\n> 这是一个%s，定义见 [DDL](%s)。\n", map[TableKind]string{
			KindView: "视图", KindMatView: "物化视图",
		}[t.Kind], path.Base(tablePath(t, ".sql")))
	}

	b.WriteString("\n| 列 | 类型 | 约束 | 默认 | 说明 |\n| --- | --- | --- | --- | --- |\n")
	for _, c := range t.Columns {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s |\n",
			c.Name, c.Type, columnTraits(t, c), mdCode(c.Default), mdCell(c.Comment))
	}

	if idx := orderedConstraints(t); len(idx) > 0 {
		b.WriteString("\n## 约束\n\n| 名称 | 定义 |\n| --- | --- |\n")
		for _, c := range idx {
			fmt.Fprintf(&b, "| `%s` | %s |\n", c.Name, mdCode(c.Def))
		}
	}
	if len(t.Indexes) > 0 {
		b.WriteString("\n## 索引\n\n| 名称 | 定义 |\n| --- | --- |\n")
		for _, i := range t.Indexes {
			fmt.Fprintf(&b, "| `%s` | %s |\n", i.Name, mdCode(i.Def))
		}
	}
	if len(t.Triggers) > 0 {
		b.WriteString("\n## 触发器\n\n| 名称 | 定义 |\n| --- | --- |\n")
		for _, tr := range t.Triggers {
			fmt.Fprintf(&b, "| `%s` | %s |\n", tr.Name, mdCode(tr.Def))
		}
	}

	// 反向引用是 DDL 给不了的信息，也是「改这张表会影响谁」唯一的答案来源。
	if refs := referrers(t.Name, edges); len(refs) > 0 {
		b.WriteString("\n## 被引用\n\n| 来源表 | 外键列 |\n| --- | --- |\n")
		for _, e := range refs {
			fmt.Fprintf(&b, "| [`%s`](%s) | `%s` |\n",
				e.Child, relLink(self, mdPathOf(s, e.Child)), e.Label)
		}
	}

	// 一跳邻域图是「上百张表怎么看」的真正答案：全局图看清有哪些簇，
	// 单表页看清这张表周围长什么样。
	names, near := neighborhood(t.Name, edges)
	if len(near) > 0 {
		diagram, err := mermaid(names, near, "")
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n## 邻域\n\n本表 + 直接外键邻居。全局分簇见 [SCHEMA.md](%s)。\n\n"+
			"```mermaid\n%s```\n", relLink(self, docFile), diagram)
	}

	fmt.Fprintf(&b, "\n---\n\n[DDL](%s) · [← 总览](%s)\n",
		path.Base(tablePath(t, ".sql")), relLink(self, docFile))
	return b.String(), nil
}

// columnTraits 把这一列身上的约束压成一格可读文本。
func columnTraits(t Table, c Column) string {
	var out []string
	for _, k := range orderedConstraints(t) {
		if !slices.Contains(k.Columns, c.Name) {
			continue
		}
		switch k.Type {
		case ConstraintPrimaryKey:
			out = append(out, "PK")
		case ConstraintUnique:
			out = append(out, "UNIQUE")
		case ConstraintForeignKey:
			ref := k.RefTable
			if len(k.RefColumns) > 0 {
				ref += "." + strings.Join(k.RefColumns, ",")
			}
			out = append(out, "FK→`"+ref+"`")
		}
	}
	if c.NotNull && !slices.Contains(out, "PK") {
		out = append(out, "NOT NULL")
	}
	if len(out) == 0 {
		return ""
	}
	return strings.Join(out, " · ")
}

// referrers 返回指向 table 的全部外键边（已按 edgesOf 的顺序稳定）。
func referrers(table string, edges []fkEdge) []fkEdge {
	var out []fkEdge
	for _, e := range edges {
		if e.Parent == table && e.Child != table {
			out = append(out, e)
		}
	}
	return out
}

// ---------- 总览 ----------

func renderOverview(s Schema, edges []fkEdge) (string, error) {
	var biz, fw []Table
	for _, t := range s.Tables {
		if t.Framework() {
			fw = append(fw, t)
		} else {
			biz = append(biz, t)
		}
	}

	var b strings.Builder
	b.WriteString(mdHeader)
	fmt.Fprintf(&b, "\n# %s schema\n\n", s.Name)
	fmt.Fprintf(&b, "%d 张业务表，%d 张 appkit 基础设施表。"+
		"本文件与 `%s/` 由 `make schema` 从 `%s` 生成——"+
		"改表结构永远是新开一个迁移文件，然后重新生成。\n",
		len(biz), len(fw), schemaDir, migrationsDir)

	if len(biz) == 0 {
		b.WriteString("\n本域尚无业务表：先写第一个建表迁移，别忘了 `COMMENT ON TABLE`。\n")
	} else {
		b.WriteString("\n## 表清单\n\n| 表 | 列 | 说明 |\n| --- | --- | --- |\n")
		for _, t := range biz {
			desc := mdCell(t.Comment)
			if t.Comment == "" {
				desc = noComment
			}
			fmt.Fprintf(&b, "| [`%s`](%s) | %d | %s |\n",
				t.Name, relLink(docFile, tablePath(t, ".md")), len(t.Columns), desc)
		}
		if hasMissingComment(biz) {
			fmt.Fprintf(&b, "\n> 标了 %s 的表，在它的建表迁移里补一句 "+
				"`COMMENT ON TABLE %s.<表> IS '…'`——表的用途属于 schema 设计，"+
				"写在迁移里才会跟着表一起演进，写在外部文档里必腐。\n", noComment, s.Name)
		}
		rel, err := renderRelations(biz, edges)
		if err != nil {
			return "", err
		}
		b.WriteString(rel)
	}

	if len(s.Enums) > 0 {
		b.WriteString("\n## 枚举类型\n\n| 类型 | 取值 |\n| --- | --- |\n")
		for _, e := range s.Enums {
			vals := make([]string, len(e.Values))
			for i, v := range e.Values {
				vals[i] = "`" + v + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s |\n", e.Name, mdCell(strings.Join(vals, " · ")))
		}
	}

	// 只列签名不列函数体：函数体是代码，事实源在迁移文件里。列出来是为了
	// 不静默漏东西——一个 schema 里有函数却只字不提，读者会以为没有。
	if len(s.Functions) > 0 {
		b.WriteString("\n## 函数\n\n| 名称 | 参数 | 返回 |\n| --- | --- | --- |\n")
		for _, f := range s.Functions {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", f.Name, mdCode(f.Signature), mdCode(f.Returns))
		}
	}

	if len(fw) > 0 {
		names := make([]string, len(fw))
		for i, t := range fw {
			names[i] = "`" + t.Name + "`"
		}
		fmt.Fprintf(&b, "\n## appkit 基础设施表\n\n%s——由框架建表并维护，"+
			"每个域仓库都一样，结构见 [`%s/%s/`](%s/%s)。\n",
			strings.Join(names, " · "), schemaDir, fwSubdir, path.Base(schemaDir), fwSubdir)
	}
	return b.String(), nil
}

// renderRelations 输出按外键连通性分簇的关系图。
func renderRelations(biz []Table, edges []fkEdge) (string, error) {
	inBiz := map[string]bool{}
	for _, t := range biz {
		inBiz[t.Name] = true
	}
	comps := components(Schema{Tables: biz})

	var clusters [][]string
	var isolated []string
	for _, c := range comps {
		if len(c) == 1 {
			isolated = append(isolated, c[0])
			continue
		}
		clusters = append(clusters, c)
	}
	sort.Strings(isolated)

	var b strings.Builder
	b.WriteString("\n## 关系图\n\n")
	if len(clusters) == 0 && len(isolated) == len(biz) {
		b.WriteString("本域的表之间还没有外键关联。\n")
	} else {
		b.WriteString("按外键连通性分簇。单张图挤得看不动时，" +
			"看每张表自己的一跳邻域图（点表名进去）。\n")
	}
	for i, c := range clusters {
		d, err := mermaid(c, edges, "")
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "\n### 簇 %d · %d 张表\n\n```mermaid\n%s```\n", i+1, len(c), d)
	}
	if len(isolated) > 0 && len(clusters) > 0 {
		names := make([]string, len(isolated))
		for i, n := range isolated {
			names[i] = "`" + n + "`"
		}
		fmt.Fprintf(&b, "\n### 无外键关联\n\n%s\n", strings.Join(names, " · "))
	}
	return b.String(), nil
}

func hasMissingComment(ts []Table) bool {
	for _, t := range ts {
		if t.Comment == "" {
			return true
		}
	}
	return false
}

// mdPathOf 返回 name 表的 .md 产出路径（找不到时退回业务表布局）。
func mdPathOf(s Schema, name string) string {
	for _, t := range s.Tables {
		if t.Name == name {
			return tablePath(t, ".md")
		}
	}
	return path.Join(schemaDir, name+".md")
}

// ---------- 小工具 ----------

// mdCell 把任意文本塞进 Markdown 表格的一格：竖线会截断表格、换行会终结整行。
func mdCell(v string) string {
	v = strings.ReplaceAll(v, "|", `\|`)
	return strings.Join(strings.Fields(v), " ")
}

// mdCode 同 mdCell，非空时再包一层反引号。
func mdCode(v string) string {
	if v == "" {
		return ""
	}
	return "`" + mdCell(v) + "`"
}

// relLink 计算从 from 文件指向 to 文件的相对链接（纯斜杠，不走 filepath——
// 生成物必须在 Windows 上逐字节一致）。
func relLink(from, to string) string {
	fromDir := strings.Split(path.Dir(from), "/")
	toParts := strings.Split(to, "/")
	i := 0
	for i < len(fromDir) && i < len(toParts)-1 && fromDir[i] == toParts[i] {
		i++
	}
	out := make([]string, 0, len(fromDir)-i+len(toParts)-i)
	for range fromDir[i:] {
		out = append(out, "..")
	}
	return path.Join(append(out, toParts[i:]...)...)
}
