-- Code generated by appkit db-access. DO NOT EDIT.
-- service: admin_api
-- manifest-sha256: fa45bc384716d6ec9522bf3fc90e05b2883157e2c93cba286bb9b01e98179f3a
-- Append this output as a new migration; never replace an applied migration.

SELECT pg_advisory_xact_lock(hashtextextended('appkit:db-access:role:app_admin_api', 0));
DO $appkit$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin_api') THEN
        BEGIN
            CREATE ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT;
        EXCEPTION
            WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role
        END;
    END IF;
END
$appkit$;
ALTER ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT;

GRANT "app_admin_api" TO "psp_admin_api";
GRANT "app_admin_channel_test" TO "psp_admin_api";
DO $appkit$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin') THEN
        EXECUTE format('REVOKE %I FROM %I', 'app_admin', 'psp_admin_api');
    END IF;
END
$appkit$;
GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";
GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT SELECT, USAGE ON SEQUENCE "merchant"."admin_account_id_seq" TO "app_admin_api";
GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";
LOCK TABLE "merchant"."admin_account" IN ACCESS EXCLUSIVE MODE;
DO $appkit$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'merchant' AND tablename = 'admin_account' AND policyname = 'admin_account_tenant_isolation') THEN
        RAISE EXCEPTION 'required RLS policy % is missing on %', 'admin_account_tenant_isolation', 'merchant.admin_account';
    END IF;
END
$appkit$;
ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "merchant"."admin_account" FORCE ROW LEVEL SECURITY;
REVOKE DELETE, INSERT, TRIGGER, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";
DO $appkit$
DECLARE
    appkit_column text;
BEGIN
    FOR appkit_column IN SELECT a.attname FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'ledger' AND c.relname = 'ledger_entry' AND a.attnum > 0 AND NOT a.attisdropped LOOP
        EXECUTE format('REVOKE INSERT (%I), UPDATE (%I) ON TABLE %I.%I FROM %I', appkit_column, appkit_column, 'ledger', 'ledger_entry', 'app_admin_api');
    END LOOP;
END
$appkit$;
REVOKE TRIGGER, TRUNCATE ON TABLE "merchant"."admin_account" FROM "app_admin_api";
