-- Code generated by appkit db-access. DO NOT EDIT.
-- service: admin_api
-- manifest-sha256: 0c8020f60c9dd560f012ddb70bd9aa24dccc624a85d0a0f351a6b961dd50d1a8
-- Append this output as a new migration; never replace an applied migration.

SELECT pg_advisory_xact_lock(hashtextextended('appkit:db-access:role:app_admin_api', 0));
DO $appkit$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin_api') THEN
        BEGIN
            CREATE ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT;
        EXCEPTION
            WHEN duplicate_object OR unique_violation THEN NULL; -- concurrent migration created the same cluster-wide role
        END;
    END IF;
END
$appkit$;
ALTER ROLE "app_admin_api" NOLOGIN NOBYPASSRLS NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT;

GRANT "app_admin_api" TO "psp_admin_api";
GRANT "app_admin_channel_test" TO "psp_admin_api";
DO $appkit$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin') THEN
        EXECUTE format('REVOKE %I FROM %I', 'app_admin', 'psp_admin_api');
    END IF;
END
$appkit$;
GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";
GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT SELECT, USAGE ON SEQUENCE "merchant"."admin_account_id_seq" TO "app_admin_api";
GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";
LOCK TABLE "merchant"."admin_account" IN ACCESS EXCLUSIVE MODE;
DO $appkit$
DECLARE
    appkit_actual_policies text[];
BEGIN
    SELECT COALESCE(array_agg(p.polname::text ORDER BY p.polname::text), ARRAY[]::text[]) INTO appkit_actual_policies FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'merchant' AND c.relname = 'admin_account';
    IF appkit_actual_policies <> ARRAY['admin_account_tenant_isolation']::text[] THEN
        RAISE EXCEPTION 'RLS policy set mismatch on %: expected %, actual %', 'merchant.admin_account', ARRAY['admin_account_tenant_isolation']::text[], appkit_actual_policies;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'merchant' AND c.relname = 'admin_account' AND p.polname = 'admin_account_tenant_isolation' AND p.polcmd = '*' AND p.polpermissive = TRUE AND ARRAY(SELECT CASE WHEN policy_role.role_oid = 0 THEN 'PUBLIC' ELSE r.rolname::text END FROM unnest(p.polroles) AS policy_role(role_oid) LEFT JOIN pg_roles r ON r.oid = policy_role.role_oid ORDER BY 1) = ARRAY['PUBLIC']::text[] AND pg_get_expr(p.polqual, p.polrelid) IS NOT DISTINCT FROM 'true' AND pg_get_expr(p.polwithcheck, p.polrelid) IS NOT DISTINCT FROM 'true') THEN
        RAISE EXCEPTION 'RLS policy % definition mismatch on %', 'admin_account_tenant_isolation', 'merchant.admin_account';
    END IF;
END
$appkit$;
ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "merchant"."admin_account" FORCE ROW LEVEL SECURITY;
REVOKE DELETE, INSERT, TRIGGER, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";
DO $appkit$
DECLARE
    appkit_column text;
BEGIN
    FOR appkit_column IN SELECT a.attname FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'ledger' AND c.relname = 'ledger_entry' AND a.attnum > 0 AND NOT a.attisdropped LOOP
        EXECUTE format('REVOKE INSERT (%I), UPDATE (%I) ON TABLE %I.%I FROM %I', appkit_column, appkit_column, 'ledger', 'ledger_entry', 'app_admin_api');
    END LOOP;
END
$appkit$;
REVOKE TRIGGER, TRUNCATE ON TABLE "merchant"."admin_account" FROM "app_admin_api";
