-- Code generated by appkit db-access. DO NOT EDIT.
-- service: admin_api
-- manifest-sha256: fa45bc384716d6ec9522bf3fc90e05b2883157e2c93cba286bb9b01e98179f3a
-- Append this output as a new migration; never replace an applied migration.

DO $appkit$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_admin_api') THEN
        CREATE ROLE "app_admin_api" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT;
    END IF;
END
$appkit$;
ALTER ROLE "app_admin_api" NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE INHERIT;

GRANT "app_admin_api" TO "psp_admin_api";
GRANT "app_admin_channel_test" TO "psp_admin_api";
REVOKE "app_admin" FROM "psp_admin_api";
GRANT USAGE ON SCHEMA "merchant" TO "app_admin_api";
GRANT INSERT, SELECT, UPDATE ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT SELECT, USAGE ON SEQUENCE "merchant"."admin_account_id_seq" TO "app_admin_api";
GRANT SELECT ("encrypted_key") ON TABLE "merchant"."admin_account" TO "app_admin_api";
GRANT EXECUTE ON FUNCTION "merchant"."search_admin_account_keys"("text", "pg_catalog"."uuid") TO "app_admin_api";
ALTER TABLE "merchant"."admin_account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "merchant"."admin_account" FORCE ROW LEVEL SECURITY;
DO $appkit$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'merchant' AND tablename = 'admin_account' AND policyname = 'admin_account_tenant_isolation') THEN
        RAISE EXCEPTION 'required RLS policy % is missing on %', 'admin_account_tenant_isolation', 'merchant.admin_account';
    END IF;
END
$appkit$;
REVOKE DELETE, INSERT, TRIGGER, TRUNCATE, UPDATE ON TABLE "ledger"."ledger_entry" FROM "app_admin_api";
REVOKE TRIGGER, TRUNCATE ON TABLE "merchant"."admin_account" FROM "app_admin_api";
