package scaffold

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/forgeplex/appkit/ruleset"
)

// domainWantFiles 是域仓库骨架的完整文件集（name=ledger），
// 含 new 时物化的 lint / CI 配置（ruleset.Sync）与运行配置。
var domainWantFiles = []string{
	".appkit.yml",
	".gitignore",
	".gitattributes",
	"Makefile",
	"README.md",
	"AGENTS.md",
	"CLAUDE.md",
	"go.mod",
	"ledger.go",
	"cmd/ledgerd/main.go",
	"config/dev.yaml",
	"internal/ledger/service.go",
	"internal/ledger/store.go",
	"internal/ledger/errors.go",
	"internal/postgres/store.go",
	"internal/http/handler.go",
	"internal/inbox/consumer.go",
	"internal/module/module.go",
	"db/migrations/0001_appkit_base.sql",
	"db/queries/example.sql",
	"sqlc.yaml",
	".golangci.yml",
	".go-arch-lint.yml",
	".github/workflows/ci.yml",
}

func TestDomainScaffold(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "ledger")
	if err := Domain(Options{Name: "ledger", Dir: dir, AppkitVersion: "(devel)"}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}

	assertFileSet(t, dir, domainWantFiles)
	assertRendered(t, dir)
	assertGoParses(t, dir)
	assertGofmt(t, dir)

	t.Run("基础迁移含建 schema 与四张基础设施表", func(t *testing.T) {
		sql := readFile(t, dir, "db/migrations/0001_appkit_base.sql")
		mustContain(t, "0001_appkit_base.sql", sql,
			// CREATE SCHEMA 是给 sqlc 静态分析看的（运行期 pgmigrate 幂等重建）。
			`CREATE SCHEMA IF NOT EXISTS "ledger";`,
			`CREATE TABLE IF NOT EXISTS "ledger".outbox`,
			`CREATE TABLE IF NOT EXISTS "ledger".inbox`,
			`CREATE TABLE IF NOT EXISTS "ledger"."idempotency_keys"`,
			`CREATE TABLE IF NOT EXISTS "ledger".audit_log`,
			// 框架建的表也得有说明——否则 db/SCHEMA.md 里一半的表在教域作者
			// 补 COMMENT，另一半是框架自己没补的。机检见 internal/schemadoc
			// 的 TestFrameworkTablesAllDocumented。
			`COMMENT ON TABLE "ledger".outbox IS '`,
			`COMMENT ON TABLE "ledger".inbox IS '`,
			`COMMENT ON TABLE "ledger"."idempotency_keys" IS '`,
			`COMMENT ON TABLE "ledger".audit_log IS '`,
		)
	})

	t.Run("运行配置与最小模式", func(t *testing.T) {
		mustContain(t, "config/dev.yaml", readFile(t, dir, "config/dev.yaml"),
			"database:", `url: ""`, "LEDGERD_DATABASE__URL", "fail closed", "debug:", "pprof: false")
		// 总线/迁移器/遥测的装配已收进 bootstrap（生成物里不再出现，
		// 也就改不坏）；main 只声明最小模式装什么。
		mustContain(t, "main.go", readFile(t, dir, "cmd/ledgerd/main.go"),
			"appkit.ModuleFunc(", "最小模式", "Minimal: minimal")
		mustContain(t, "Makefile", readFile(t, dir, "Makefile"),
			"run-minimal:", "-minimal", "正常启动必须有 database.url")
		mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
			"outbox.NewRelay(", `reg.Worker("outbox-relay"`)
	})

	t.Run("lint 与 CI 配置已物化", func(t *testing.T) {
		mustContain(t, ".golangci.yml", readFile(t, dir, ".golangci.yml"),
			"Code generated by appkit sync")
		mustContain(t, ".github/workflows/ci.yml", readFile(t, dir, ".github/workflows/ci.yml"),
			"domain-ci.yml")
	})

	t.Run("appkit.yml", func(t *testing.T) {
		yml := readFile(t, dir, ".appkit.yml")
		mustContain(t, ".appkit.yml", yml,
			"version: 1",
			"kind: domain",
			"domain: ledger",
			"module: github.com/forgeplex/ledger",
			"allowRequires: []",
		)
	})

	t.Run("go.mod devel 提示联调", func(t *testing.T) {
		gomod := readFile(t, dir, "go.mod")
		mustContain(t, "go.mod", gomod,
			"module github.com/forgeplex/ledger",
			"appkit dev",
			"github.com/jackc/pgx/v5 v5.",
		)
		// devel 模式不 require appkit：对不存在版本的 require 会让
		// go 命令去代理拉取而失败，appkit 由 go.work 提供。
		if strings.Contains(gomod, "require github.com/forgeplex/appkit") ||
			strings.Contains(gomod, "\tgithub.com/forgeplex/appkit") {
			t.Errorf("devel 模式 go.mod 不应 require appkit：\n%s", gomod)
		}
	})

	t.Run("关键内容", func(t *testing.T) {
		mustContain(t, "ledger.go", readFile(t, dir, "ledger.go"),
			"package ledger", "go:embed db/migrations/*.sql", "func Module(")
		mustContain(t, "Makefile", readFile(t, dir, "Makefile"),
			"run github.com/forgeplex/appkit/cmd/appkit check",
			"sqlc/cmd/sqlc@", "dev-db", "run-db",
			// 迁移可单独施加：生产上这一步在 initContainer/Job 里跑。
			"migrate: dev-db", "./cmd/ledgerd -migrate",
			// schema 文档要能一条命令重新生成，否则「产出禁手改」就只是句空话：
			// 没人愿意为了改一行注释去手搓 DSN。
			"schema: dev-db", "cmd/appkit schema -dsn '$(DEV_DB_URL)'",
			// lint 与 CI 必须钉同一版本（ruleset 是唯一事实源），
			// 否则「本地绿、CI 红」，而且查起来最费劲。
			"golangci-lint@"+ruleset.GolangciLintVersion,
			"go-arch-lint@"+ruleset.ArchLintVersion,
			// appkit-lint 进 make lint：版本取法与 domain-ci.yml 一致。
			"lint/cmd/appkit-lint@$(APPKITLINT_VERSION)", "APPKITLINT_VERSION ?=")
		mustContain(t, "main.go", readFile(t, dir, "cmd/ledgerd/main.go"),
			"bootstrap.Main(bootstrap.Options{", `Service: "ledgerd"`,
			"Modules: func(d bootstrap.Deps)", "ledger.Module(")
		mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
			`Schema = "ledger"`, "reg.Migrations(Schema", "reg.Health(", "appkit.Provide(",
			// 权限码声明从第一天就在骨架里：目录由各域自声明、框架汇总，
			// 组合根不再手抄全目录。
			"reg.Permissions(", `"ledger:read"`)
		sqlcYml := readFile(t, dir, "sqlc.yaml")
		mustContain(t, "sqlc.yaml", sqlcYml,
			"internal/postgres/sqlc", `schema: "db/migrations"`,
			// 金额 override 只能指向 pgx 编得进/扫得出的类型。money.Money
			// 编译期无感、运行期扫描失败——那是真库用例的职责，这里先锁住
			// 不得退回（TestDomainNumericOverrideRoundTrips 负责正向验证）。
			`go_type: "github.com/shopspring/decimal.Decimal"`,
			"不用 money.Money")
		// 注释里可以解释为什么不用它，但 go_type 不许指回去。
		if strings.Contains(sqlcYml, `go_type: "github.com/forgeplex/appkit/money.Money"`) {
			t.Error("sqlc.yaml 不得把 NUMERIC override 指向 money.Money：运行期无法扫描（真库机检见 domain_db_test.go）")
		}
		mustContain(t, "README.md", readFile(t, dir, "README.md"),
			"appkit sync", "appkit dev", "make migrate", "MIGRATION_DRIFT",
			"make schema", "db/SCHEMA.md",
			"make lint")
		// 迁移参与 sha256 校验：换行必须跨平台一致，否则 Windows 上 checkout
		// 就会触发误报的 MIGRATION_DRIFT。
		mustContain(t, ".gitattributes", readFile(t, dir, ".gitattributes"),
			"*.sql text eol=lf", "linguist-generated=true",
			// schema 产出是生成物：PR 里折叠，让「有人手改了它」更打眼。
			"db/SCHEMA.md             linguist-generated=true",
			"db/schema/**             linguist-generated=true")
		// AGENTS.md 是 AI 代理唯一会读的规程：新增的框架能力必须在这里出现，
		// 否则代理会照旧手写 goroutine / ticker / 埋点。
		mustContain(t, "AGENTS.md", readFile(t, dir, "AGENTS.md"),
			"reg.Worker(", "job.Every(", "callctx.From(ctx)",
			// 出站 HTTP 的正解是装 Transport，不是逐调用点写 Inject——
			// 规程指错机制，代理就会照着摊到每个调用点的那种写法写。
			"callctx.Transport",
			// Conform 的元数据传播检查是自愿项：规程不提，就没人填，
			// 那它和不存在没区别。
			"SeenMeta",
			// 迁移是追加日志，一张表的真实形状散在 N 个文件里。规程不指向
			// db/schema/，代理就会继续在脑子里重放整条迁移历史（并且重放错）。
			"db/schema/", "make schema", "COMMENT ON TABLE",
			// 缺 COMMENT 的两处点名（文档 ⚠ 与 CI ::warning）用的是同一条
			// 谓词——规程只说一处，代理就不知道另一处也是软的、可以补。
			"::warning",
			"MIGRATION_DRIFT", "make migrate", "apptest.Conform",
			// 幂等的两个注入口：不写进规程，代理就只会裸套中间件，
			// "80"/"80.00" 的重试撞 422、多租户手拼前缀这些问题一个都躲不掉。
			"idem.WithCanonicalizer", "idem.WithKeyScope",
			"make lint")
		// 规程里不许出现假的强制力：appkit-lint 已接进 make lint 与 CI，
		// 规程就不许再说"没有机检"（反向同样成立——哪天机检撤了，这句
		// 断言会逼着把规程改回诚实的说法）。
		if agents := readFile(t, dir, "AGENTS.md"); strings.Contains(agents, "没有机检") ||
			!strings.Contains(agents, "appkit-lint") {
			t.Error("AGENTS.md 对金额规则的强制力描述与现状不符（appkit-lint 已在 make lint 与 CI）")
		}
	})
}

// TestDomainGoModVersioned 断言发布版本直接写进 require，不留占位提示。
func TestDomainGoModVersioned(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "pay")
	if err := Domain(Options{
		Name: "pay", AppkitVersion: "v0.7.3", Dir: dir,
		WorkflowRef: "0123456789abcdef0123456789abcdef01234567",
	}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	gomod := readFile(t, dir, "go.mod")
	mustContain(t, "go.mod", gomod, "github.com/forgeplex/appkit v0.7.3")
	if strings.Contains(gomod, "appkit dev") {
		t.Error("发布版本的 go.mod 不应含 devel 联调提示")
	}
}

// TestDomainCustomModule 断言 -module 覆盖默认 module path。
func TestDomainCustomModule(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "ledger")
	err := Domain(Options{Name: "ledger", Module: "example.com/x/ledgerx", Dir: dir}, nil)
	if err != nil {
		t.Fatalf("Domain: %v", err)
	}
	mustContain(t, "go.mod", readFile(t, dir, "go.mod"), "module example.com/x/ledgerx")
	mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
		`"example.com/x/ledgerx/internal/ledger"`)
}

// TestDomainCompiles 用 go.work（use 本地 appkit）完整编译生成仓库。
func TestDomainCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("short 模式跳过编译")
	}
	dir := filepath.Join(t.TempDir(), "ledger")
	if err := Domain(Options{Name: "ledger", Dir: dir}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	buildGenerated(t, dir)
}

// TestDomainPartitionedScaffold 断言 -partitioned 形态：无前缀迁移、路由装配
// （NewRouted + Schemas 注入 + 每分区 relay），且单形态的痕迹（CREATE SCHEMA、
// const Schema、带前缀规则）不出现。
func TestDomainPartitionedScaffold(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "rbac")
	if err := Domain(Options{Name: "rbac", Dir: dir, AppkitVersion: "(devel)", Partitioned: true}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}

	assertRendered(t, dir)
	assertGoParses(t, dir)
	assertGofmt(t, dir)

	t.Run("基础迁移无前缀", func(t *testing.T) {
		sql := readFile(t, dir, "db/migrations/0001_appkit_base.sql")
		mustContain(t, "0001_appkit_base.sql", sql,
			`CREATE TABLE IF NOT EXISTS outbox`,
			`CREATE TABLE IF NOT EXISTS inbox`,
			`CREATE TABLE IF NOT EXISTS idempotency_keys`,
			`CREATE TABLE IF NOT EXISTS audit_log`,
			`COMMENT ON TABLE outbox IS '`,
		)
		// 分区域域不能写死 schema：CREATE SCHEMA 与任何 "rbac". 前缀都不许出现
		// （schema 名是组合根注入的分区映射的知识，迁移文件里无从得知）。
		if strings.Contains(sql, "CREATE SCHEMA") || strings.Contains(sql, `"rbac".`) {
			t.Errorf("分区域域的基础迁移不得出现定死的 schema：\n%s", sql)
		}
	})

	t.Run("路由装配", func(t *testing.T) {
		mod := readFile(t, dir, "internal/module/module.go")
		mustContain(t, "module.go", mod,
			"Schemas map[string]string",
			"pgtx.NewRouted(",
			"callctx.From(ctx).TenantID",
			"routePartition(",
			`apperr.InvalidArgument(`,
			"outbox.Publish(ctx, pgtx.From(ctx, p.pool), schema, evt)",
			`reg.Worker("outbox-relay/"+tenant`,
			// 权限码是应用级目录，分区形态同样声明。
			"reg.Permissions(", `"rbac:read"`,
		)
		// 单形态的痕迹不得出现。
		for _, gone := range []string{`Schema = "rbac"`, "pgtx.New(m.opts.Pool)", "outbox.NewPublisher("} {
			if strings.Contains(mod, gone) {
				t.Errorf("分区域域的 module.go 不应出现 %q", gone)
			}
		}
	})

	t.Run("main 注入演示分区映射", func(t *testing.T) {
		mustContain(t, "main.go", readFile(t, dir, "cmd/rbacd/main.go"),
			`Schemas: map[string]string{"tenant": "rbac_tenant"}`)
	})

	t.Run("SQL 前缀规则翻转", func(t *testing.T) {
		mustContain(t, ".appkit.yml", readFile(t, dir, ".appkit.yml"), "partitioned: true")
		mustContain(t, "example.sql", readFile(t, dir, "db/queries/example.sql"), "不带 schema 前缀")
		mustContain(t, "sqlc.yaml", readFile(t, dir, "sqlc.yaml"), "无前缀")
		mustContain(t, "store.go", readFile(t, dir, "internal/postgres/store.go"),
			"必须在事务内", "search_path")
	})

	t.Run("AGENTS 与 README 翻转", func(t *testing.T) {
		agents := readFile(t, dir, "AGENTS.md")
		mustContain(t, "AGENTS.md", agents,
			"分区域域", "SET LOCAL search_path", "不带 schema 前缀",
			// 命令清单里不许列出 make schema；提它的地方只能是「不适用」的说明。
			"make schema` 不适用本形态")
		mustContain(t, "README.md", readFile(t, dir, "README.md"),
			"-partitioned", "分区域域")
	})
}

// TestDomainPartitionedCompiles 编译分区域域生成仓库（同 TestDomainCompiles）。
func TestDomainPartitionedCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("short 模式跳过编译")
	}
	dir := filepath.Join(t.TempDir(), "rbac")
	if err := Domain(Options{Name: "rbac", Dir: dir, Partitioned: true}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	buildGenerated(t, dir)
}

// TestDomainTenantScaffold 断言 -tenant 形态：NewTenant 事务、Setup 期 RLS
// 校验、0002 样例迁移（tenant_id + 三件套），且单形态的痕迹（裸 pgtx.New）
// 不出现。
func TestDomainTenantScaffold(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "crm")
	if err := Domain(Options{Name: "crm", Dir: dir, AppkitVersion: "(devel)", Tenant: true}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}

	assertRendered(t, dir)
	assertGoParses(t, dir)
	assertGofmt(t, dir)

	t.Run("基础迁移带策略函数", func(t *testing.T) {
		sql := readFile(t, dir, "db/migrations/0001_appkit_base.sql")
		mustContain(t, "0001_appkit_base.sql", sql,
			// 基础表照旧（单 schema 形态不变）……
			`CREATE TABLE IF NOT EXISTS "crm".outbox`,
			// ……只追加策略函数（DDL 来自库函数，事实源不在模板）。
			`CREATE OR REPLACE FUNCTION "crm".appkit_current_tenant()`)
	})

	t.Run("租户装配", func(t *testing.T) {
		mod := readFile(t, dir, "internal/module/module.go")
		mustContain(t, "module.go", mod,
			"pgtx.NewTenant(m.opts.Pool)",
			// Setup 期守卫必须在：迁移先于 Setup 应用，这里看到的是终态。
			"pgtx.VerifyTenantRLS(ctx, m.opts.Pool, Schema)",
			// 权限码声明与其他形态一致（目录是应用级的）。
			"reg.Permissions(", `"crm:read"`,
		)
		// 单形态的痕迹不得出现。
		for _, gone := range []string{"pgtx.New(m.opts.Pool)", "pgtx.NewRouted("} {
			if strings.Contains(mod, gone) {
				t.Errorf("租户域的 module.go 不应出现 %q", gone)
			}
		}
	})

	t.Run("样例迁移三件套", func(t *testing.T) {
		sql := readFile(t, dir, "db/migrations/0002_demo_notes.sql")
		mustContain(t, "0002_demo_notes.sql", sql,
			`tenant_id text NOT NULL`,
			`CREATE INDEX notes_tenant_idx ON "crm".notes (tenant_id, created_at)`,
			`COMMENT ON TABLE "crm".notes IS`,
			`ALTER TABLE "crm"."notes" ENABLE ROW LEVEL SECURITY`,
			`ALTER TABLE "crm"."notes" FORCE ROW LEVEL SECURITY`,
			`CREATE POLICY tenant_isolation ON "crm"."notes"`,
			// 教学注释必须点到 verify——建真表照抄的读者得知道漏挂的后果。
			"VerifyTenantRLS",
		)
	})

	t.Run("规程翻转", func(t *testing.T) {
		mustContain(t, "AGENTS.md", readFile(t, dir, "AGENTS.md"),
			"租户域", "RLS 三件套", "callctx.From(ctx).TenantID",
			// 建表纪律要指向样例，否则代理建新表会漏挂三件套。
			"0002_demo_notes.sql")
		mustContain(t, "README.md", readFile(t, dir, "README.md"),
			"-tenant", "租户域", "BYPASSRLS")
	})
}

// TestDomainTenantCompiles 编译租户域生成仓库（同 TestDomainCompiles）。
func TestDomainTenantCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("short 模式跳过编译")
	}
	dir := filepath.Join(t.TempDir(), "crm")
	if err := Domain(Options{Name: "crm", Dir: dir, Tenant: true}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	buildGenerated(t, dir)
}

// TestDomainFormFlagsMutuallyExclusive 锁住形态互斥：行级隔离与 schema 隔离
// 不组合，同时给两个 flag 必须当场报错而不是生成一个四不像。
func TestDomainFormFlagsMutuallyExclusive(t *testing.T) {
	err := Domain(Options{Name: "crm", Dir: filepath.Join(t.TempDir(), "crm"),
		Partitioned: true, Tenant: true}, nil)
	if err == nil || !strings.Contains(err.Error(), "互斥") {
		t.Fatalf("-tenant 与 -partitioned 同给应报互斥错误，实际 %v", err)
	}
}
