package scaffold

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/forgeplex/appkit/ruleset"
)

// domainWantFiles 是域仓库骨架的完整文件集（name=ledger），
// 含 new 时物化的 lint / CI 配置（ruleset.Sync）与运行配置。
var domainWantFiles = []string{
	".appkit.yml",
	".gitignore",
	".gitattributes",
	"Makefile",
	"README.md",
	"AGENTS.md",
	"CLAUDE.md",
	"go.mod",
	"ledger.go",
	"cmd/ledgerd/main.go",
	"config/dev.yaml",
	"internal/ledger/service.go",
	"internal/ledger/store.go",
	"internal/ledger/errors.go",
	"internal/postgres/store.go",
	"internal/http/handler.go",
	"internal/inbox/consumer.go",
	"internal/module/module.go",
	"db/migrations/0001_appkit_base.sql",
	"db/queries/example.sql",
	"sqlc.yaml",
	".golangci.yml",
	".go-arch-lint.yml",
	".github/workflows/ci.yml",
}

func TestDomainScaffold(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "ledger")
	if err := Domain(Options{Name: "ledger", Dir: dir, AppkitVersion: "(devel)"}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}

	assertFileSet(t, dir, domainWantFiles)
	assertRendered(t, dir)
	assertGoParses(t, dir)
	assertGofmt(t, dir)

	t.Run("基础迁移含建 schema 与四张基础设施表", func(t *testing.T) {
		sql := readFile(t, dir, "db/migrations/0001_appkit_base.sql")
		mustContain(t, "0001_appkit_base.sql", sql,
			// CREATE SCHEMA 是给 sqlc 静态分析看的（运行期 pgmigrate 幂等重建）。
			`CREATE SCHEMA IF NOT EXISTS "ledger";`,
			`CREATE TABLE IF NOT EXISTS "ledger".outbox`,
			`CREATE TABLE IF NOT EXISTS "ledger".inbox`,
			`CREATE TABLE IF NOT EXISTS "ledger"."idempotency_keys"`,
			`CREATE TABLE IF NOT EXISTS "ledger".audit_log`,
			// 框架建的表也得有说明——否则 db/SCHEMA.md 里一半的表在教域作者
			// 补 COMMENT，另一半是框架自己没补的。机检见 internal/schemadoc
			// 的 TestFrameworkTablesAllDocumented。
			`COMMENT ON TABLE "ledger".outbox IS '`,
			`COMMENT ON TABLE "ledger".inbox IS '`,
			`COMMENT ON TABLE "ledger"."idempotency_keys" IS '`,
			`COMMENT ON TABLE "ledger".audit_log IS '`,
		)
	})

	t.Run("运行配置与最小模式", func(t *testing.T) {
		mustContain(t, "config/dev.yaml", readFile(t, dir, "config/dev.yaml"),
			"database:", `url: ""`, "LEDGERD_DATABASE__URL")
		// 总线/迁移器/遥测的装配已收进 bootstrap（生成物里不再出现，
		// 也就改不坏）；main 只声明最小模式装什么。
		mustContain(t, "main.go", readFile(t, dir, "cmd/ledgerd/main.go"),
			"appkit.ModuleFunc(", "最小模式", "Minimal: minimal")
		mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
			"outbox.NewRelay(", `reg.Worker("outbox-relay"`)
	})

	t.Run("lint 与 CI 配置已物化", func(t *testing.T) {
		mustContain(t, ".golangci.yml", readFile(t, dir, ".golangci.yml"),
			"Code generated by appkit sync")
		mustContain(t, ".github/workflows/ci.yml", readFile(t, dir, ".github/workflows/ci.yml"),
			"domain-ci.yml")
	})

	t.Run("appkit.yml", func(t *testing.T) {
		yml := readFile(t, dir, ".appkit.yml")
		mustContain(t, ".appkit.yml", yml,
			"version: 1",
			"kind: domain",
			"domain: ledger",
			"module: github.com/forgeplex/ledger",
			"allowRequires: []",
		)
	})

	t.Run("go.mod devel 提示联调", func(t *testing.T) {
		gomod := readFile(t, dir, "go.mod")
		mustContain(t, "go.mod", gomod,
			"module github.com/forgeplex/ledger",
			"appkit dev",
			"github.com/jackc/pgx/v5 v5.",
		)
		// devel 模式不 require appkit：对不存在版本的 require 会让
		// go 命令去代理拉取而失败，appkit 由 go.work 提供。
		if strings.Contains(gomod, "require github.com/forgeplex/appkit") ||
			strings.Contains(gomod, "\tgithub.com/forgeplex/appkit") {
			t.Errorf("devel 模式 go.mod 不应 require appkit：\n%s", gomod)
		}
	})

	t.Run("关键内容", func(t *testing.T) {
		mustContain(t, "ledger.go", readFile(t, dir, "ledger.go"),
			"package ledger", "go:embed db/migrations/*.sql", "func Module(")
		mustContain(t, "Makefile", readFile(t, dir, "Makefile"),
			"run github.com/forgeplex/appkit/cmd/appkit check",
			"sqlc/cmd/sqlc@", "dev-db", "run-db",
			// 迁移可单独施加：生产上这一步在 initContainer/Job 里跑。
			"migrate: dev-db", "./cmd/ledgerd -migrate",
			// schema 文档要能一条命令重新生成，否则「产出禁手改」就只是句空话：
			// 没人愿意为了改一行注释去手搓 DSN。
			"schema: dev-db", "cmd/appkit schema -dsn '$(DEV_DB_URL)'",
			// lint 与 CI 必须钉同一版本（ruleset 是唯一事实源），
			// 否则「本地绿、CI 红」，而且查起来最费劲。
			"golangci-lint@"+ruleset.GolangciLintVersion,
			"go-arch-lint@"+ruleset.ArchLintVersion,
			// appkit-lint 进 make lint：版本取法与 domain-ci.yml 一致。
			"lint/cmd/appkit-lint@$(APPKITLINT_VERSION)", "APPKITLINT_VERSION ?=")
		mustContain(t, "main.go", readFile(t, dir, "cmd/ledgerd/main.go"),
			"bootstrap.Main(bootstrap.Options{", `Service: "ledgerd"`,
			"Modules: func(d bootstrap.Deps)", "ledger.Module(")
		mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
			`Schema = "ledger"`, "reg.Migrations(Schema", "reg.Health(", "appkit.Provide(")
		sqlcYml := readFile(t, dir, "sqlc.yaml")
		mustContain(t, "sqlc.yaml", sqlcYml,
			"internal/postgres/sqlc", `schema: "db/migrations"`,
			// 金额 override 只能指向 pgx 编得进/扫得出的类型。money.Money
			// 编译期无感、运行期扫描失败——那是真库用例的职责，这里先锁住
			// 不得退回（TestDomainNumericOverrideRoundTrips 负责正向验证）。
			`go_type: "github.com/shopspring/decimal.Decimal"`,
			"不用 money.Money")
		// 注释里可以解释为什么不用它，但 go_type 不许指回去。
		if strings.Contains(sqlcYml, `go_type: "github.com/forgeplex/appkit/money.Money"`) {
			t.Error("sqlc.yaml 不得把 NUMERIC override 指向 money.Money：运行期无法扫描（真库机检见 domain_db_test.go）")
		}
		mustContain(t, "README.md", readFile(t, dir, "README.md"),
			"appkit sync", "appkit dev", "make migrate", "MIGRATION_DRIFT",
			"make schema", "db/SCHEMA.md",
			"make lint")
		// 迁移参与 sha256 校验：换行必须跨平台一致，否则 Windows 上 checkout
		// 就会触发误报的 MIGRATION_DRIFT。
		mustContain(t, ".gitattributes", readFile(t, dir, ".gitattributes"),
			"*.sql text eol=lf", "linguist-generated=true",
			// schema 产出是生成物：PR 里折叠，让「有人手改了它」更打眼。
			"db/SCHEMA.md             linguist-generated=true",
			"db/schema/**             linguist-generated=true")
		// AGENTS.md 是 AI 代理唯一会读的规程：新增的框架能力必须在这里出现，
		// 否则代理会照旧手写 goroutine / ticker / 埋点。
		mustContain(t, "AGENTS.md", readFile(t, dir, "AGENTS.md"),
			"reg.Worker(", "job.Every(", "callctx.From(ctx)",
			// 出站 HTTP 的正解是装 Transport，不是逐调用点写 Inject——
			// 规程指错机制，代理就会照着摊到每个调用点的那种写法写。
			"callctx.Transport",
			// Conform 的元数据传播检查是自愿项：规程不提，就没人填，
			// 那它和不存在没区别。
			"SeenMeta",
			// 迁移是追加日志，一张表的真实形状散在 N 个文件里。规程不指向
			// db/schema/，代理就会继续在脑子里重放整条迁移历史（并且重放错）。
			"db/schema/", "make schema", "COMMENT ON TABLE",
			"MIGRATION_DRIFT", "make migrate", "apptest.Conform",
			"make lint")
		// 规程里不许出现假的强制力：appkit-lint 已接进 make lint 与 CI，
		// 规程就不许再说"没有机检"（反向同样成立——哪天机检撤了，这句
		// 断言会逼着把规程改回诚实的说法）。
		if agents := readFile(t, dir, "AGENTS.md"); strings.Contains(agents, "没有机检") ||
			!strings.Contains(agents, "appkit-lint") {
			t.Error("AGENTS.md 对金额规则的强制力描述与现状不符（appkit-lint 已在 make lint 与 CI）")
		}
	})
}

// TestDomainGoModVersioned 断言发布版本直接写进 require，不留占位提示。
func TestDomainGoModVersioned(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "pay")
	if err := Domain(Options{Name: "pay", AppkitVersion: "v0.7.3", Dir: dir}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	gomod := readFile(t, dir, "go.mod")
	mustContain(t, "go.mod", gomod, "github.com/forgeplex/appkit v0.7.3")
	if strings.Contains(gomod, "appkit dev") {
		t.Error("发布版本的 go.mod 不应含 devel 联调提示")
	}
}

// TestDomainCustomModule 断言 -module 覆盖默认 module path。
func TestDomainCustomModule(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "ledger")
	err := Domain(Options{Name: "ledger", Module: "example.com/x/ledgerx", Dir: dir}, nil)
	if err != nil {
		t.Fatalf("Domain: %v", err)
	}
	mustContain(t, "go.mod", readFile(t, dir, "go.mod"), "module example.com/x/ledgerx")
	mustContain(t, "module.go", readFile(t, dir, "internal/module/module.go"),
		`"example.com/x/ledgerx/internal/ledger"`)
}

// TestDomainCompiles 用 go.work（use 本地 appkit）完整编译生成仓库。
func TestDomainCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("short 模式跳过编译")
	}
	dir := filepath.Join(t.TempDir(), "ledger")
	if err := Domain(Options{Name: "ledger", Dir: dir}, nil); err != nil {
		t.Fatalf("Domain: %v", err)
	}
	buildGenerated(t, dir)
}
