package scaffold

import (
	"bytes"
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
)

// The tool intentionally uses only existing public pgmigrate/pgx APIs. Shipping
// source lets a domain adopt schema snapshots without an unreleased dependency,
// pg_dump version coupling or changing its runtime module graph.
//
//go:embed schematool/*.go
var schemaToolFS embed.FS

const schemaToolHeader = "// Code generated by appkit schema-tool. DO NOT EDIT.\n"

// SchemaToolFiles is shared by new-domain scaffolding and explicit installation
// in existing repositories. There is one maintained copy of the generator.
func SchemaToolFiles() (map[string][]byte, error) {
	entries, err := fs.ReadDir(schemaToolFS, "schematool")
	if err != nil {
		return nil, err
	}
	files := make(map[string][]byte, len(entries))
	for _, entry := range entries {
		body, err := schemaToolFS.ReadFile("schematool/" + entry.Name())
		if err != nil {
			return nil, err
		}
		files["internal/postgres/schematool/"+entry.Name()] = append([]byte(schemaToolHeader), body...)
	}
	return files, nil
}

// InstallSchemaTool only replaces its own generated files. It does not modify
// migrations, sqlc configuration, dependencies or any database.
func InstallSchemaTool(dir string) error {
	var err error
	dir, err = filepath.Abs(dir)
	if err != nil {
		return err
	}
	files, err := SchemaToolFiles()
	if err != nil {
		return err
	}
	for path := range files {
		abs := filepath.Join(dir, filepath.FromSlash(path))
		for ancestor := abs; ancestor != filepath.Clean(dir); ancestor = filepath.Dir(ancestor) {
			info, err := os.Lstat(ancestor)
			if err != nil && !os.IsNotExist(err) {
				return err
			}
			if err == nil && info.Mode()&os.ModeSymlink != 0 {
				return fmt.Errorf("refuse schema tool symlink: %s", ancestor)
			}
			if filepath.Dir(ancestor) == ancestor {
				return fmt.Errorf("invalid schema tool repository path: %s", dir)
			}
		}
		body, err := os.ReadFile(abs)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if err == nil && !bytes.HasPrefix(body, []byte(schemaToolHeader)) {
			return fmt.Errorf("refuse to overwrite handwritten schema tool: %s", path)
		}
	}
	return writeRenderedFiles(dir, files)
}
