// Code generated by appkit gen. DO NOT EDIT.

package greetapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/forgeplex/appkit/apperr"
	"github.com/forgeplex/appkit/callctx"
	"github.com/forgeplex/appkit/contract"
)

// Client 是 greet 契约的远程绑定：与进程内 wrapper（wrap.gen.go）实现
// 同一个 Service 接口，方法体同样经 contract.Call——事务守卫、ctx 防火墙、
// 超时与错误规范化在两种部署形态下完全一致（DESIGN §5.3）。
type Client struct {
	base string
	hc   *http.Client
}

// NewClient 返回契约 client。base 是服务根地址（如 "http://ledger:8080"），
// caller 填本服务名（callctx 白名单的归因值）。
//
// 白名单传播焊死在装配处：hc 为 nil 走默认 Transport；非 nil 时在其
// Transport 外包一层 callctx.Transport（不改调用方的 client）。
// 「忘了装 Transport」这个静默失效形态在生成 client 里不存在。
func NewClient(base, caller string, hc *http.Client) *Client {
	if hc == nil {
		hc = &http.Client{}
	}
	inner := *hc
	inner.Transport = callctx.Transport{Base: hc.Transport, Caller: caller}
	return &Client{base: strings.TrimSuffix(base, "/"), hc: &inner}
}

// 编译期断言：Client 与 Service 漂移时本包编译失败。
var _ Service = (*Client)(nil)

func (c *Client) Greet(ctx context.Context, req GreetRequest) (GreetReply, error) {
	return retryUnavailable(ctx, func() (GreetReply, error) {
		return contract.Call(ctx, "greet", "Greet", 0, func(ctx context.Context) (GreetReply, error) {
			body, err := json.Marshal(req)
			if err != nil {
				return GreetReply{}, apperr.Internal(err)
			}
			hreq, err := http.NewRequestWithContext(ctx, http.MethodPost, c.base+"/greet", bytes.NewReader(body))
			if err != nil {
				return GreetReply{}, apperr.Internal(err)
			}
			hreq.Header.Set("Content-Type", "application/json")
			return do[GreetReply](c.hc, hreq)
		})
	})
}

// do 执行一次 HTTP 调用并按契约约定解码：200 解析 JSON 响应体，其余
// 状态一律经 apperr.FromProblem 重建错误——错误身份 = 错误码，跨网络重建后
// apperr.Is 判定与进程内一致。网络层故障折叠为 CodeUnavailable（可重试信号）。
func do[T any](hc *http.Client, hreq *http.Request) (T, error) {
	var zero T
	resp, err := hc.Do(hreq)
	if err != nil {
		return zero, apperr.Unavailable(err)
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return zero, apperr.Unavailable(err)
	}
	if resp.StatusCode != http.StatusOK {
		return zero, apperr.FromProblem(resp.StatusCode, raw)
	}
	var v T
	if err := json.Unmarshal(raw, &v); err != nil {
		return zero, apperr.Internal(err)
	}
	return v, nil
}

// 重试策略是合约的一部分，不由调用点自由发挥：次数封顶、间隔固定。
const (
	retryMaxAttempts = 3
	retryBackoff     = 100 * time.Millisecond
)

// retryUnavailable 仅包裹声明了 idempotent 的契约方法：只有失败是可重试信号
// （CodeUnavailable——网络错误、502–504、对端超时，契约边界统一折叠）才再试，
// 其余错误码是确定性的业务结果，重试只会放大伤害。非幂等方法不生成此调用——
// 「重复执行是否安全」是方法的语义属性，声明在 contract.yaml 里。
func retryUnavailable[T any](ctx context.Context, fn func() (T, error)) (T, error) {
	v, err := fn()
	for attempt := 1; attempt < retryMaxAttempts && err != nil && apperr.Is(err, apperr.CodeUnavailable); attempt++ {
		timer := time.NewTimer(retryBackoff * time.Duration(attempt))
		select {
		case <-ctx.Done():
			timer.Stop()
			return v, err
		case <-timer.C:
		}
		v, err = fn()
	}
	return v, err
}
