// Code generated by appkit gen. DO NOT EDIT.

package greetapi

import "github.com/forgeplex/appkit/apperr"

// 错误码常量：错误身份 = 错误码，判定用 apperr.Is(err, Code...)，
// 单体与微服务两种部署形态下行为一致。
const (
	CodeGreetUnsupportedLang = "GREET_UNSUPPORTED_LANG"
)

// 错误 sentinel：不可变模板，可安全共享；附加上下文用 WithDetail/WithCause。
var (
	ErrGreetUnsupportedLang = apperr.New(CodeGreetUnsupportedLang, 422, "不支持的问候语言")
)
