// Code generated by appkit gen. DO NOT EDIT.

package greetapi

import (
	"encoding/json"
	"net/http"

	"github.com/forgeplex/appkit/apperr"
	"github.com/forgeplex/appkit/callctx"
)

// NewHTTPHandler 把 Service 暴露为 HTTP：每方法一条 POST 路由，请求体
// JSON decode，错误经 apperr.WriteProblem，成功 200 JSON。与 client.gen.go
// 由同一份 contract.yaml 生成，编解码约定只有一份。装配形态：
//
//	mux.Handle("/", greetapi.NewHTTPHandler(greetapi.WrapService(impl, 0)))
func NewHTTPHandler(svc Service) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /greet", func(w http.ResponseWriter, r *http.Request) {
		var req GreetRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			apperr.WriteProblem(w, apperr.InvalidArgument("请求体不是合法 JSON"))
			return
		}
		reply, err := svc.Greet(r.Context(), req)
		if err != nil {
			apperr.WriteProblem(w, err)
			return
		}
		writeJSON(w, reply)
	})
	return serve(mux)
}

// serve 是入站白名单的兜底：挂在 httpserver.RequestID 中间件链后时是
// 幂等重放（请求头与 ctx 本就是同一份事实），裸挂时把请求头里的
// callctx.Meta 搬进 ctx——契约 handler 挂在哪，元数据都到得了实现。
// request id 的生成与响应回写仍是外层中间件的职责，这里不越权。
func serve(mux *http.ServeMux) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mux.ServeHTTP(w, r.WithContext(callctx.Merge(r.Context(), callctx.Extract(r.Header.Get))))
	})
}

// writeJSON 是成功响应的唯一出口。
func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}
