// Code generated by appkit gen. DO NOT EDIT.

package greetapi

import "context"

// GreetRequest 是 Greet 的请求 DTO：契约边界传值、可序列化。
type GreetRequest struct {
	// Name 必填。
	Name string `json:"name"`
	Lang string `json:"lang"`
}

// GreetReply 是 Greet 的响应 DTO。
type GreetReply struct {
	Message string `json:"message"`
}

// Service 是 greet 域的契约接口（事实源 contract.yaml）。进程内 wrapper
// 与远程 client 实现同一个接口，调用方无从（也不需要）分辨对端形态。
type Service interface {
	// Greet 打招呼。lang 空值等价 "en"；不支持的语言返回 GREET_UNSUPPORTED_LANG。幂等：重复执行安全，client 会对可用性故障做有界重试。
	Greet(ctx context.Context, req GreetRequest) (GreetReply, error)
}
