// Code generated by appkit gen. DO NOT EDIT.

package greetapi

import (
	"context"
	"time"

	"github.com/forgeplex/appkit/contract"
)

// wrappedService 是 Service 的契约边界 wrapper：每个方法体经 contract.Call
// 获得事务守卫、ctx 防火墙、独立超时与错误规范化（DESIGN §5.3）。
type wrappedService struct {
	inner   Service
	timeout time.Duration
}

// WrapService 把实现包进契约边界，供 appkit.ProvideContract 使用；
// timeout <= 0 时使用 contract.DefaultTimeout。
func WrapService(inner Service, timeout time.Duration) Service {
	if timeout <= 0 {
		timeout = contract.DefaultTimeout
	}
	return wrappedService{inner: inner, timeout: timeout}
}

func (w wrappedService) Greet(ctx context.Context, req GreetRequest) (GreetReply, error) {
	return contract.Call(ctx, "greet", "Greet", w.timeout, func(ctx context.Context) (GreetReply, error) {
		return w.inner.Greet(ctx, req)
	})
}
